### ISSUE TITLE
Order of search results

### ISSUE THREAD

**Issue by cabotine** [wort-schule/wort.schule#10]
Show the best fitting results first (starting with the same letters as search term)

**Comment by wintermeyer** [comment]
@cabotine Please provide a couple of examples. What is searched for and how the results should be displayed.

**Comment by wintermeyer** [comment]
<img width="1189" alt="Bildschirmfoto 2022-11-02 um 08 02 34" src="https://user-images.githubusercontent.com/69770/199421949-465ed14c-76f7-41c1-b70a-7801f80a982c.png">

**Comment by wintermeyer** [comment]
Will be tackled by https://github.com/wort-schule/wort.schule/issues/67
