### ISSUE TITLE
Images do not show up anymore

### ISSUE THREAD

**Issue by cabotine** [wort-schule/wort.schule#101]
Apparently, the images links (profile image and word images) are broken:
![grafik](https://user-images.githubusercontent.com/8180537/205848401-516be1c6-23d4-435f-8ff8-1881717f0003.png)
Dont know how to describe it better.

**Comment by wintermeyer** [comment]
<img width="1153" alt="Bildschirm­foto 2022-12-06 um 08 44 17" src="https://user-images.githubusercontent.com/69770/205851255-994152c8-c315-4f47-adc1-5cea3866c8bb.png">

**Comment by phylor** [comment]
This is most definitely a routing issue :see_no_evil:
