### ISSUE TITLE
Enrich the School model with an address

### ISSUE THREAD

**Issue by wintermeyer** [wort-schule/wort.schule#106]
We need to enrich the `School` model. The following attributes have to be added:

- street: string
- zip_code: string. validates_presence_of
- city: string. validates_presence_of
- country: string. validates_presence_of
- homepage_url: string (validates :url, url: { allow_blank: true } -> https://github.com/perfectline/validates_url)
- email: string
- phone_number: string
- fax_number: string

In addition to that we need to add a paper trail for this model. It should record who changed what.

**Comment by cabotine** [comment]
I am sorry, I have not checked it before: it might be helpful to have the "Bundesland/Kanton" field.

**Comment by wintermeyer** [comment]
> I am sorry, I have not checked it before: it might be helpful to have the "Bundesland/Kanton" field.

https://github.com/wort-schule/wort.schule/issues/128
