### ISSUE TITLE
Pretty URLs which work with human-friendly strings

### ISSUE THREAD

**Issue by wintermeyer** [wort-schule/wort.schule#11]
Currently the word "Affe" is accessible via the URL https://wort.schule/nouns/19 which is not very human friendly. It would be nicer to have it accessible via the URL https://wort.schule/affe. Easier for humans and SEO would benefit too. Obviously it should work with all word types not just with nouns.
 
- [x] We still have to be able to access stuff like the admin page or the impressum. Maybe we should create a save path /intern for those. That would mean that impressum moves to /intern/impressum and admin to /intern/admin, etc.
- [x] Sometimes a word has multiple entries (e.g. "Bauer" https://wort.schule/?filterrific%5Bfilter_wordcontains%5D=Bauer). For those we have to add some sort of additional sequence. That "sequence" should be human readable and child friendly. Not a generic UUID. Adding the Thema could be a potential solution. Or an integer number sequence.
- [x] The link https://wort.schule/nouns/19 should not be used in the application any more if possible. It should always be https://wort.schule/affe
- [x] Add these paths to the robots.txt to not be crawl able by search engines:
  - https://wort.schule/nouns/
  - https://wort.schule/verbs/
  - https://wort.schule/adjectives/

I guess https://github.com/norman/friendly_id is a good gem for this but I am open for all good solutions.

**Comment by phylor** [comment]
We need to take a decision here because of technical constraints:

1. Technically easy, with little changes is a slug scoped by the word type. The URL would be: `https://wort.schule/nouns/affe`.
2. If we want to use the same slug for all word types (`https://wort.schule/affe`), we need to include the word type when a conflict occurs.

    For example: `ticken` (noun), `ticken-verb`

    This solution also requires migrating from the current multiple table inheritance to a single table inheritance. I assume that setup will then work, but further issues could arise.

@wintermeyer What do you think?

**Comment by wintermeyer** [comment]
> 1. Technically easy, with little changes is a slug scoped by the word type. The URL would be: `https://wort.schule/nouns/affe`.
> 2. If we want to use the same slug for all word types (`https://wort.schule/affe`)

**We need to have https://wort.schule/affe** and not https://wort.schule/nouns/affe. This is a feature which aims to make life easier for humans. Adding `/nouns` into the path doesn't make it easy.

> we need to include the word type when a conflict occurs.

Do we? We could create a new table just for this which uses polymorphic associations to the other tables and add friendly_id to that new table. One can argue about the cleanliness of this approach but it is not totally dirty.

@phylor What do you think?

**Comment by wintermeyer** [comment]
> My issue is not necessarily with the technical implementation, but that the URLs are not specific enough to specify the word. Examples:
> 
> There are many nouns/verbs, e.g.: `Ticken` (noun), `ticken` (verb) There are also verbs/adjectives, e.g.: `erwachsen`, which can be either a verb or an adjective.

An 80% solution is better here than not having this feature at all. I hear you and I understand the problem. But I prefer to have the 80% to be as simple and easy as possible. But maybe we can ease the 20% - and I don't really think we are talking about 20% but that is a different discussion - by adding a feature (an additional table field) that a human can use to offer the system a good `slug` for the given word. So if an editor doesn't like the automated slug he/she can offer a different slug and if that is not already take we use that.

## Brainstorming

We can discuss an alternative way of solving the problem. We could display an index page when ever a URL is used which leads to multiple possible solutions (e.g. https://wort.schule/bauer or https://wort.schule/erwachsen). On that index page we would list all those possible solutions. I am open to this but we would have to bend friendly_id for this.

**Comment by cabotine** [comment]
We also have the issue of having nouns with multiple meanings which are more than once in our database (like Schloss (castle) and Schloss (lock)).

It maybe a solution to check if the search result contains one word (in that case it would show the one word) or if the search result contains more than one word and than it would show the overview.

Therefor we would need a search across word types (which we need anyway ;)  see https://github.com/wort-schule/wort.schule/issues/5). But then we would just have https://wort.schule/Schloss or https://wort.schule/ticken


Best
Frank J.

**Comment by cabotine** [comment]
Sorry just saw the Brainstorming (which is the same solution)
It could be https://wort.schule/Schloss-intId could be the link to the page (or https://wort.schule/Schloss-Burg and https://wort.schule/Schloss-Tuerschloss

**Comment by wintermeyer** [comment]
- There is no 100% perfect solution for all cases.
- The current (old) solution is bad for all cases.
- The https://wort.schule/schloss and https://wort.schule/schloss-2 solution is perfect for 80% and better than currently for the other 20%.
- We can move to the brainstorming index method in the future in case it is needed. We don't have to implement it right now. We don't lose that possibility.

**But** we can add a link or button (somewhere in the red area) with information that there are other words which are the same but have different meanings and link to a search for that words (e.g. "2 andere Schlösser"). That search result would be an index view for that word.

<img width="377" alt="Bildschirmfoto 2022-11-05 um 11 29 34" src="https://user-images.githubusercontent.com/69770/200115516-08691398-b567-49c6-ac95-4a6fe2cf37a4.png">

**Comment by wintermeyer** [comment]
> **But** we can add a link or button (somewhere in the red area) with information that there are other words which are the same but have different meanings and link to a search for that words (e.g. "2 andere Schlösser"). That search result would be an index view for that word.

Let's use "2 weitere Wörter" which is a bit more generic and we know how much real estate this button uses.

**Comment by cabotine** [comment]
Maybe "2 weitere Bedeutungen" (2 more meanings) instead of 2 more words... You know German teachers are smartasses... :)
