### ISSUE TITLE
Multiple Wording

### ISSUE THREAD

**Issue by wintermeyer** [wort-schule/wort.schule#111]
German teachers have different flavours for the same Wortart. 

- Nomen or Substantive or Namenwörter
- Verben or Tunwörter
- Adjektive or Wie-Wörter or Eigenschaftswörter

Right now we use Substantiv for a Substantiv. A young student might have a problem with this wording because his/her teacher uses Namenwort for the same thing. 

@xamiam Can we find a way of displaying all different versions on the same view or do we have to solve this with a I18n translation table?

<img width="1153" alt="Bildschirm­foto 2022-12-06 um 11 54 43" src="https://user-images.githubusercontent.com/69770/205893111-685a51db-1813-4f36-aeea-d3d83a65d485.png">

**Comment by philipp-kempgen** [comment]
And the list above isn't even complete. Hauptwörter, Bindewörter …

**Comment by wintermeyer** [comment]
> And the list above isn't even complete. Hauptwörter, Bindewörter …

@cabotine Anything else?

**Comment by cabotine** [comment]
I ll have to ask our german didactics specialist.

**Comment by cabotine** [comment]
I have spoken to her:
we have three options:
Nomen Verben Adjektive
Substantive Verben Adjektive
Namenwörter Tu-Wörter wie-Wörter

and two for genus:
Maskulinum Feminum Neutrum
männlich weiblich sächlich

**Comment by phylor** [comment]
- [ ] Einstellung für  `Singular/Plural - Singularwort/Pluralwort`, `Einzahl/Mehrzahl - Einzahlwort/Mehrzahlwort`
