### ISSUE TITLE
Phonetics search needs sorting

### ISSUE THREAD

**Issue by cabotine** [wort-schule/wort.schule#118]
Phonetics is cool.
There are cases where the sorting would be really helpful, especially the "C, G, K" cases. If your search for a word with K or G in the beginning you need to wriggle through the words with C.
![grafik](https://user-images.githubusercontent.com/8180537/206392004-a28b85dd-7f4b-4dbb-914d-cce90f4e925c.png)

Is the phonetics search always activated in regular search at the moment? It feels like it.

**Comment by wintermeyer** [comment]
I'll close this for now because of #67

**Comment by wintermeyer** [comment]
Phonetics search is always fuzzy. It will always create edge cases. It is a 80% solution. It is better than not having it but there is no way we can create the perfect search and the perfect sorting. We do have bigger fish to fry right now. Let's stick with a "this is useful but not perfect" solution right now.

**Comment by wintermeyer** [comment]
@xamiam It would be nice to have a way to show the user that this word was a "Treffer" because of phonetic search.
