### ISSUE TITLE
"Silbenbögen" in Themes

### ISSUE THREAD

**Issue by cabotine** [wort-schule/wort.schule#119]
This is what we can achieve using the font:
![grafik](https://user-images.githubusercontent.com/8180537/206419455-99091e1b-4c7e-4623-a903-19fab6db3597.png)
Do you have an example how the solution with CSS and the box-model could look like? Then I could create a comparison and we can see what we gain or loose by which effort.

**Comment by wintermeyer** [comment]
Background: The aim is to have the Silbenbögen as an option on Wortkarten.

**Comment by philipp-kempgen** [comment]
SVG could be an option. Animated “Silbenbögen” FTW! :-)
https://ishadeed.com/article/custom-underline-svg/
The font looks good though.

**Comment by frankjmueller** [comment]
Das kann dann, glaube ich, geschlossen werden, oder?
