### ISSUE TITLE
Layout for detail pages

### ISSUE THREAD

**Issue by xamiam** [wort-schule/wort.schule#153]
Here are the layouts for the detail page. Changes will be added to this Issue. @wintermeyer 

![wort schule_v4_detail_desktop](https://user-images.githubusercontent.com/309421/214272391-57d923d2-8ab0-4abd-8717-65fec27ed5f2.png)

![wort schule_v4_detail_mobile](https://user-images.githubusercontent.com/309421/214272395-08a780ed-c44e-4c2d-8ab0-e0bd624585b0.png)

**Comment by cabotine** [comment]
I really like it! Thank you! The example sentence(s) and the audio-player(s) for those need to go somewhere. 
And the coloured icon (a red circle for female nouns, a  blue one for male nouns and a green one for neutral) would be great in front or below the article.

**Comment by frankjmueller** [comment]
Das kann dann, glaube ich, geschlossen werden, oder?
