### ISSUE TITLE
TTS für Beispielsätze

### ISSUE THREAD

**Issue by wintermeyer** [wort-schule/wort.schule#169]
Die Beispielsätze sollen auch als Audio zur Verfügung stellen.

**Comment by phortx** [comment]
@phylor @wintermeyer Welches Model ist das?

**Comment by phylor** [comment]
> @phylor @wintermeyer Welches Model ist das?

Beispielsätze werden als JSONB Array direkt auf `Word#example_sentences` gespeichert: https://github.com/wort-schule/wort.schule/blob/5c9842df38e640aa61a99f6e96831061d92bf77f/db/schema.rb#L412

Geparst werden muss aber nichts, `noun.example_sentences` gibt direkt einen Array zurück. Jeder Eintrag ist dabei ein Beispielsatz.
