### ISSUE TITLE
Neue Haupt-/Indexseite

### ISSUE THREAD

**Issue by wintermeyer** [wort-schule/wort.schule#170]
Dieses Issue ist das Ergebnis vom Issue https://github.com/wort-schule/wort.schule/issues/67 und ein paar offsite Gesprächen.  
Ich versuche das Issue so genau wie möglich zu schreiben, ohne zu sehr in technische Details zu gehen. Wie immer: Falls etwas technisch keinen Sinn macht, bitte zum Issue hinzufügen und @wintermeyer CCen.

Die neue Haupt-/Indexseite soll einfacher und schneller erfassbar werden. Der folgende Screenshot sagt mehr als 1.000 Worte. Es geht aber **nicht um eine pixelgenaue Umsetzung**! Es soll mit Tailwind CSS Bordmitteln so gut es geht umgesetzt werden ohne sich im Klein-Klein zu verirren. Bei Design-Fragen steht @xamiam und @wintermeyer zur Verfügung.

![205975941-af534b3e-6066-4473-bdbe-7e3cd5fc9a16](https://user-images.githubusercontent.com/69770/220394661-eea436e5-0fbb-4fa9-93ad-7adf87e4476f.png)

To-Dos:
- [x] Top Navigation Bar aufräumen. Nur noch links den Namen der Seite und rechts die Option einzuloggen. Keep it simple!
- [x] Wenn die Seite aufgerufen wird, soll der Focus direkt im Eingabeformular sein.
- [x] Bei jeder Eingabe werden die 8 besten Treffer direkt unter dem Eingabefeld angezeigt. In der Art und Weise des Screenshots. ACHTUNG: Bei dieser Suche wird **nicht** phonetisch gesucht! Die Sortierung der Treffer erfolgt a) anhand der Position des Treffers (Wortanfang hat eine höhere Priorität als die Wortmitte), b) nach dem Alphabet. Die Funktionalität der Suche und Sortierung solle in einer eigenen Methode abgebildet werden, die später erweitert oder verbessert werden kann.
- [x] An Ende gibt es noch einen Button, der die Anzahl der Treffer anzeigt.
- [ ] Bei der mobilen Variante, sollte das Eingabefeld nach der ersten Eingabe nach oben positioniert werden. So das der zur Verfügung stehende Real-Estate besser genutzt wird. Wir müssen dann auch testen, ob 8 beste Treffer eine sinnvolle Zahl ist. Mobile First!
- [x] Wenn der User ein bestimmtes Wort anklickt, dann wird direkt zu diesem Wort gegangen. Wenn der User auf Enter drückt (bzw. die Buttons klickt), dann wird die Suchergebnisseite (#171) angezeigt.
- [x] Logo oben links in Navigation ersetzen

**Comment by cabotine** [comment]
@wintermeyer Does it make sense to use that logo version (upper left corner)?
![Logo final Quadrat mit Schrift(2)](https://user-images.githubusercontent.com/8180537/220406997-dc0c3e92-4cd0-434f-884c-087e54e3d498.svg)

**Comment by wintermeyer** [comment]
> @wintermeyer Does it make sense to use that logo version (upper left corner)?

That is a duplication. We already have the logo very big and visible in the middle of the screen. I want to keep this page as minimalistic as possible. No visual "Störfaktoren" what so ever.

**Comment by cabotine** [comment]
Okay. ;)

**Comment by phylor** [comment]
@wintermeyer Bezüglich Navigation:

1. Wir entfernen überall `Substantive`, `Verben` und `Adjektive`, korrekt?
2. Wohin kommen die restlichen Navigationspunkte, bzw. wo kommt man auf diese Seiten?

![image](https://user-images.githubusercontent.com/1394828/220922861-1ab07aac-00ff-4a2a-a18f-937470fd1cf5.png)

Oder soll *nur* die Homepage so aussehen? Aber auf allen anderen Seiten ist die komplette Navigation sichtbar? Falls dem so ist, gibt es einen Unterschied zwischen eingeloggtem User und Gast?

**Comment by wintermeyer** [comment]
> @wintermeyer Bezüglich Navigation:
> 
> 1. Wir entfernen überall `Substantive`, `Verben` und `Adjektive`, korrekt?

Korrekt.

Auf der Suchergebnisseite wird es ja die Möglichkeit geben auf diese "Reiter" (mir fällt kein besserer Begriff ein) zu klicken. Es wäre nicht uncool, wenn man das in der URL abbilden könnte/würde. Aber das ist ein nice to have.

> 2. Wohin kommen die restlichen Navigationspunkte, bzw. wo kommt man auf diese Seiten?

Sehr gute Frage.

Bitte nimm sie erst mal ganz raus, eröffnet ein neues Issue mit dieser Frage und assigne es mir. Das ist ein GUI/Workflow Problem. Darüber muss ich nachdenken.

> Oder soll _nur_ die Homepage so aussehen?

Nein, ich möchte alle Seiten minimalistisch (sprich aufgeräumt) haben. Natürlich gibt es für eingeloggte User zusätzliche Menüpunkte, aber auch da keinen Zoo.

**Comment by cabotine** [comment]
Kommentar (hoffentlich hilfreich von der Seitenlinie).
Meines Erachtens ist alles unter Spezialeinträge eigentlich nur für Menschen relevant die Editierrechte haben.

Es wäre schön, wenn es irgendwo hier eine Seite mit den Links geben würde, damit wir auch in Übergangszeiten auf die Seiten kommen können.

**Comment by wintermeyer** [comment]
@phylor Bitte erstelle irgendwo eine `Sonstiges` Unterseite und kopiere alle diese Links auf diese Seite. Dann können wir uns später darum kümmern.

**Comment by phylor** [comment]
@xamiam Könntest Du mir bitte den Schriftzug oben links in der Navigation als transparentes SVG bereitstellen?

![image](https://user-images.githubusercontent.com/1394828/221256223-e6331037-f9fb-43d1-ae1f-0bccab37e3c4.png)

**Comment by wintermeyer** [comment]
> @xamiam Könntest Du mir bitte den Schriftzug oben links in der Navigation als transparentes SVG bereitstellen?

Mache es bitte erst mal als ganz normale Schrift. Lass uns mal schauen wie das aussieht. Wäre mir prinzipiell lieber als SVG. Kann man dann wenigstens sauber copy and pasten. Old school! ;-)

**Comment by phylor** [comment]
> > @xamiam Könntest Du mir bitte den Schriftzug oben links in der Navigation als transparentes SVG bereitstellen?
> 
> Mache es bitte erst mal als ganz normale Schrift. Lass uns mal schauen wie das aussieht. Wäre mir prinzipiell lieber als SVG. Kann man dann wenigstens sauber copy and pasten. Old school! ;-)

Können wir machen. Was ist es denn für eine Schrift? Wir können natürlich `sans` nehmen, die Schriften sind aber nicht so breit wie die im Design :slightly_smiling_face:

**Comment by xamiam** [comment]
Hey @phylor,

die folgenden Schrift sollte gut passen:

https://fonts.google.com/share?selection.family=Sora:wght@800

Lokalisiert gibt's die hier: 

https://gwfh.mranftl.com/fonts/sora?subsets=latin

@wintermeyer Wie ist es mit dem Logo / Schriften? Ist da schon was definiert?

**Comment by xamiam** [comment]
Ansonsten:

![wort schule](https://user-images.githubusercontent.com/309421/221331400-baf5d4eb-9ca3-489d-9740-72d354153a27.svg)

**Comment by wintermeyer** [comment]
> @wintermeyer Wie ist es mit dem Logo / Schriften? Ist da schon was definiert?

Nein. Mir wäre am liebsten etwas, das schon auf dem System ist. Wir springen durch so viele brennende Reifen, um das alles schnell zu machen, da will ich nicht WebPerformance auf der Strasse liegen lassen, nur um irgendwo eine schöne Schrift downzuloaden.

**Comment by phylor** [comment]
@wintermeyer Die Index-Controller/Views zu "Substantiven", "Verben" etc. können wir komplett entfernen, korrekt?

**Comment by wintermeyer** [comment]
> @wintermeyer Die Index-Controller/Views zu "Substantiven", "Verben" etc. können wir komplett entfernen, korrekt?

Ja, können wir entfernen. 👍

Falls man die jemals wieder brauchen sollte, kann man immer noch im Git eine Zeitreise machen.
