### ISSUE TITLE
Neue Suchergebnisseite

### ISSUE THREAD

**Issue by wintermeyer** [wort-schule/wort.schule#171]
Die hier besprochene Webseite ist das Ergebnis der Suche von https://github.com/wort-schule/wort.schule/issues/170 uns es gelten die gleichen Überlegungen wie bei #170 

# Standard

Auch hier wieder sagt ein Screenshot mehr als 1.000 Worte:

![205975940-f03b6553-2d92-4b40-85c6-6a6a10dfc3ec](https://user-images.githubusercontent.com/69770/220405243-0128ea88-2f26-418f-9ea0-9f797739e4fa.png)

Die einzelne Wortzelle bitte in einem eigenem Partial (oder vergleichbar) abbilden. Da wird sich am Inhalt noch etwas ändern.

<img width="258" alt="Bildschirm­foto 2023-02-21 um 17 37 22" src="https://user-images.githubusercontent.com/69770/220405437-7f4067ba-5652-4ed9-9e91-efeb264d0d49.png">

# Suchfilter

Wird auf Suchfilter geklickt, dann erscheint die folgende Ansicht:

![205975931-132d932b-ae47-428c-b487-363aaf0d4f0e](https://user-images.githubusercontent.com/69770/220406146-a4b27bc3-2204-40d9-878f-78ea8a96ec1e.png)

# Wortarten

Die Wortartenreiter sind natürlich auch Suchfilter. Existieren aber keine weiteren Suchfilter, dann wird das rechte Suchfilterfeld nicht angezeigt (erst wenn man auf "Suchfilter") klickt. Natürlich wird der entsprechende Reiter gehighlighted.

<img width="445" alt="Bildschirm­foto 2023-02-21 um 17 42 05" src="https://user-images.githubusercontent.com/69770/220407225-aa58b0fb-2a2a-4734-a46c-ed1036618865.png">

# Mobile Version

![205975949-e6e92522-e174-4300-a476-ebec4b49bd6d](https://user-images.githubusercontent.com/69770/220408481-dc2fe688-69cf-4127-ae10-811a349dee06.png)

![205975947-ccc588ca-ca09-4628-bf58-d03ef00a563e](https://user-images.githubusercontent.com/69770/220408504-8874bf2c-60db-4102-a936-6ca9059954b8.png)

# Saubere URL

Jede Suchergebnisseite muss über eine saubere URL gebookmarkt werden können. Je besser für den Menschen lesbar, desto besser. Irgendwas wie https://wort.schule/?q=bla&filter...

Der aktuelle Filterific Ansatz ist gut genug dafür.

# Erst mal keine phonetische Suche

Ich möchte das neue System erst mal ohne phonetische Suche ausprobieren und dann überlegen, wie wir die am Besten einbauen. Die Suche nach Zebra (https://wort.schule/?filterrific%5Bfilter_smart%5D=zebra) ist ein gutes Beispiel für das prinzipielle Problem. Dabei wird in der Ergebnisliste alles mögliche angezeigt, aber nicht https://wort.schule/zebra

Ich will die phonetische Suche auf jeden Fall anbieten. Aber innerhalb dieses Issues erst mal ohne agieren und dann später hinzufügen.

**Comment by cabotine** [comment]
Ähh. War das wirklich die letzte Fassung von @xamiam ? Hatten wir nicht eine Variante wo die Bilder rechts waren und damit es nicht zu Irritationen führt wenn keine Bilder da sind?

**Comment by wintermeyer** [comment]
> Ähh. War das wirklich die letzte Fassung von @xamiam ?

Ja, haben wir. Deshalb spreche ich an der Stelle von einem Partial. Das tauschen wir in einem anderen Issue aus.

[Partials](https://guides.rubyonrails.org/layouts_and_rendering.html#using-partials) sind Bausteine.

**Comment by wintermeyer** [comment]
> Deshalb spreche ich an der Stelle von einem Partial.

OK. Es ist eigentlich komplizierter. Aber @phylor weiß, was ich mit "Partial" meine. Damit ist jetzt sichergestellt, das wir den existierenden Code recyceln können und damit schnell zu einem Ergebnis kommen. Parallel oder seriell kann das entsprechende Partial verändert werden, ohne das der Code drum rum angepasst werden muss.

**Comment by cabotine** [comment]
Falls es sinnvoll ist die Zielstruktur für die Filter gleich von Beginn zu verwenden, füge ich hier nochmal die Liste ein:
Falls nicht: bin ich ich still. ;)

I can also be helpful ;) (not only create new problems)
Yesterday I spoke to an expert about the filter issue.

We figured out which are the filters useful for students:
Wortanfang, Wortende
Wort enthält (egal wo)
Silben
Kategorie (Hierarchien sichtbar machen)
Thema
Stichwörter
Wortart

Advanced filters (neccessary for teachers), those can be hidden and pop up if you click on "mehr Filter anzeigen"
Konsonante-Vokale-Folge
Verwendete Buchstaben (muss nur Wörter anzeigen die mit den Buchstaben bildbar sind)
Rechtschreibphänomene
Strategien
Quelle (sichtbar/unsichtbar)
Modellwort
Fremdwort (preferably is a Fremdwort or please no Fremdwort)
Zusammensetzung (preferably is a Zusammensetzung or please no Zusammensetzung )
Beispielsatz (preferably has an example sentence or has no example sentence)
Singular/Pluralwörter
Zahl der Silben
Reimwörter suchen (has Reimwörter)

Wortartspezifisch:
Substantive
Geschlecht

Adjektive
Absolutes Adjektiv
Unregelmäßige Komparation
Unregelmäßige Deklination

Verben
Subjektloses Verb
Starkes Verb
Perfektbildung über "haben"
Perfektbildung über "sein"

**Comment by wintermeyer** [comment]
> Falls es sinnvoll ist die Zielstruktur für die Filter gleich von Beginn zu verwenden, füge ich hier nochmal die Liste ein: Falls nicht: bin ich ich still. ;)

Ich sehe in erster Linie ein Zeitproblem. Deshalb habe ich es initial nicht ins Issue geschrieben.

@phylor Fire at will. Wir können das mit den Filtern später immer noch angehen. Das hat diese und nächste Woche keine Priorität.

PS: Wir müssen auf jeden Fall vermeiden daraus einen GUI GAU zu machen. Es sind schon so viele Applikationen gestorben, die GUIs hatten, auf denen man alles machen konnte. Keep it simple is paramount.
