### ISSUE TITLE
Wort Index in einem Buch Stil

### ISSUE THREAD

**Issue by wintermeyer** [wort-schule/wort.schule#184]
Aktuell sieht https://wort.schule/seite/wort-index/a so aus:

<img width="1185" alt="Bildschirm­foto 2023-02-25 um 15 57 39" src="https://user-images.githubusercontent.com/69770/221363822-0d35c5d4-4475-4046-8e23-395429a3c8ac.png">

Für den SEO-Zweck ist das ausreichend. Ich hätte es aber gerne für Menschen einen Tick mehr im Stil eines Wort Index in einem Buch.

- Weg mit den Panels
- Die Worte alle als `<li>` in einem `<ul>` anzeigen. Am liebsten in einem `<div class="grid grid-cols-3 gap-4">` System (3 Spalten) auf dem Desktop. Wird das dann auf Mobile automatisch als 1 col abgebildet? Falls nicht, bitte noch einen zweiten Eintrag nur für Mobil.
- Im Gegensatz zum Rest der Applikation macht hier "Aal, der" mehr Sinn, als "der Aal".
- Ich glaube der beste Eintrag ist `<li><a href="https://wort.schule/aal">Aal, der</a><br /><span class="text-sm">Substantiv</span></li>` (falls `span` hier nicht korrekt ist, bitte was anderes nehmen).
- Bei den Konjugationen oder Plural und so, bitte auf das Singular Wort verweisen. Ungefähr so: `<li>geaalt<br /><span class="text-sm">Verb. Partizip 2 von <a href="https://wort.schule/aalen">aalen</span></li>`
- Die Pagination gefällt mir noch nicht richtig. Gerade auf Mobile nimmt die sehr viel Real Estate ein. Mir wäre lieber so was wie hier (nur halt mit Buchstaben). Code-Beispiel weiter unten.
<img width="404" alt="Bildschirm­foto 2023-02-25 um 16 19 02" src="https://user-images.githubusercontent.com/69770/221365011-d9431594-73b9-4c3c-b064-3f397b169b14.png">
- Das die Umlaute ganz am Ende sind finde ich wenig schülergerecht. Aber laut https://de.wikipedia.org/wiki/Deutsches_Alphabet  ist das so. @cabotine : Wie ist das im Duden? Steht da das Ä hinter dem A oder ganz am Ende?
- Bitte beim PR jeweils einen Screenshot für Desktop und einen für Mobile hinzufügen.

## Pagination Beispiel Code

```
<nav class="isolate inline-flex -space-x-px rounded-md shadow-sm" aria-label="Pagination">
          <a href="#" class="relative inline-flex items-center rounded-l-md border border-gray-300 bg-white px-2 py-2 text-sm font-medium text-gray-500 hover:bg-gray-50 focus:z-20">
            <span class="sr-only">Previous</span>
            <svg class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
  <path fill-rule="evenodd" d="M12.79 5.23a.75.75 0 01-.02 1.06L8.832 10l3.938 3.71a.75.75 0 11-1.04 1.08l-4.5-4.25a.75.75 0 010-1.08l4.5-4.25a.75.75 0 011.06.02z" clip-rule="evenodd"></path>
</svg>
          </a>
          <!-- Current: "z-10 bg-indigo-50 border-indigo-500 text-indigo-600", Default: "bg-white border-gray-300 text-gray-500 hover:bg-gray-50" -->
          <a href="#" aria-current="page" class="relative z-10 inline-flex items-center border border-indigo-500 bg-indigo-50 px-4 py-2 text-sm font-medium text-indigo-600 focus:z-20">1</a>
          <a href="#" class="relative inline-flex items-center border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-gray-500 hover:bg-gray-50 focus:z-20">2</a>
          <a href="#" class="relative hidden items-center border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-gray-500 hover:bg-gray-50 focus:z-20 md:inline-flex">3</a>
          <span class="relative inline-flex items-center border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-gray-700">...</span>
          <a href="#" class="relative hidden items-center border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-gray-500 hover:bg-gray-50 focus:z-20 md:inline-flex">8</a>
          <a href="#" class="relative inline-flex items-center border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-gray-500 hover:bg-gray-50 focus:z-20">9</a>
          <a href="#" class="relative inline-flex items-center border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-gray-500 hover:bg-gray-50 focus:z-20">10</a>
          <a href="#" class="relative inline-flex items-center rounded-r-md border border-gray-300 bg-white px-2 py-2 text-sm font-medium text-gray-500 hover:bg-gray-50 focus:z-20">
            <span class="sr-only">Next</span>
            <svg class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
  <path fill-rule="evenodd" d="M7.21 14.77a.75.75 0 01.02-1.06L11.168 10 7.23 6.29a.75.75 0 111.04-1.08l4.5 4.25a.75.75 0 010 1.08l-4.5 4.25a.75.75 0 01-1.06-.02z" clip-rule="evenodd"></path>
</svg>
          </a>
        </nav>
```

**Comment by phortx** [comment]
> Das die Umlaute ganz am Ende sind finde ich wenig schülergerecht.

Der Wort-Index hat doch nur SEO Charakter, oder? Denn wenn nicht, ist die vorgeschlagene Buchstaben-Navigation wirklich nicht benutzerfreundlich :)

**Comment by wintermeyer** [comment]
> Der Wort-Index hat doch nur SEO Charakter, oder?

Jein. In erster Linie ist es für Suchmaschinen. Aber es soll auch für Menschen einen Mehrwert bringen.

**Comment by wintermeyer** [comment]
> Aber es soll auch für Menschen einen Mehrwert bringen.

Das ist mir selber aber auch erst im Laufe der Zeit klar geworden.

**Comment by phortx** [comment]
Das ist ja vollkommen okay :) Dann sollten wir auf keinen Fall die Buchstaben-Navigation mit `...` in der Mitte bauen, weil das sehr unpraktisch zu bedienen ist. Wenn ich zu "T" möchte, möchte ich nicht vorher auf "E", dann auf "I", dann auf "O" klicken müssen.

**Comment by phortx** [comment]
> Bei den Konjugationen oder Plural und so, bitte auf das Singular Wort verweisen. Ungefähr so: <li>geaalt<br /><span class="text-sm">Verb. Partizip 2 von <a href="https://wort.schule/aalen">aalen</span></li>

Aktuell werden alle Varianten der Wörter neben der Grundform dargestellt. Sollen wir das auftrennen, sodass jede Wort-Variante ihr eigenes LI-Element bekommt? Kann mir jemand sagen, wie ich das geschickt mache? Aktuell nutze ich einfach `Word.all`. Gibt es einen scope, der auch alle Wort-Varianten wie Plural, Konjugationen etc beinhaltet?

**Comment by wintermeyer** [comment]
> Aktuell werden alle Varianten der Wörter neben der Grundform dargestellt. Sollen wir das auftrennen, sodass jede Wort-Variante ihr eigenes LI-Element bekommt? 

Ja!

> Kann mir jemand sagen, wie ich das geschickt mache? Aktuell nutze ich einfach `Word.all`. Gibt es einen scope, der auch alle Wort-Varianten wie Plural, Konjugationen etc beinhaltet?

@phylor Hast Du dazu eine Idee?

@phortx Wenn das im gesamten ein zu extremer Aufwand ist, dann nimm nur die Grundform und gut ist. Das andere wäre schöner, aber done is better than perfect.

**Comment by phylor** [comment]
> > Kann mir jemand sagen, wie ich das geschickt mache? Aktuell nutze ich einfach `Word.all`. Gibt es einen scope, der auch alle Wort-Varianten wie Plural, Konjugationen etc beinhaltet?
> 
> @phylor Hast Du dazu eine Idee?

Ich bin verwirrt :laughing: Ich glaube nicht, dass wir solche Beziehungen zwischen Wörtern haben. Wir haben nur immer für die Grundform ein `Word`. Alles andere ist direkt auf diesem `Word` gespeichert.

Zum Beispiel:

```ruby
irb(main):011:0> noun = Noun.find_by(name: 'Aal')

irb(main):012:0> noun.plural # Gibt einen `String` zurück, kein `Word`
=> "Aale"
```

Hier ein Auszug aus `db/schema.rb` von `words`:

```ruby
  create_table "words", force: :cascade do |t|
    t.string "name"
    t.string "plural", default: ""
    t.string "case_1_singular", default: ""
    t.string "case_1_plural", default: ""
    t.string "case_2_singular", default: ""
    t.string "case_2_plural", default: ""
    t.string "case_3_singular", default: ""
    t.string "case_3_plural", default: ""
    t.string "case_4_singular", default: ""
    t.string "case_4_plural", default: ""
    t.string "participle", default: ""
    t.string "past_participle", default: ""
    t.string "present_singular_1", default: ""
    t.string "present_singular_2", default: ""
    t.string "present_singular_3", default: ""
    t.string "present_plural_1", default: ""
    t.string "present_plural_2", default: ""
    t.string "present_plural_3", default: ""
    t.string "past_singular_1", default: ""
    t.string "past_singular_2", default: ""
    t.string "past_singular_3", default: ""
    t.string "past_plural_1", default: ""
    t.string "past_plural_2", default: ""
    t.string "past_plural_3", default: ""
    t.string "imperative_singular"
    t.string "imperative_plural"
    t.string "comparative", default: ""
    t.string "superlative", default: ""
    t.jsonb "example_sentences", default: [], null: false
```

**Comment by wintermeyer** [comment]
> Ich bin verwirrt 😆 Ich glaube nicht, dass wir solche Beziehungen zwischen Wörtern haben. Wir haben nur immer für die Grundform ein `Word`. Alles andere ist direkt auf diesem `Word` gespeichert.
> 
> Zum Beispiel:
> 
> ```ruby
> irb(main):011:0> noun = Noun.find_by(name: 'Aal')
> 
> irb(main):012:0> noun.plural # Gibt einen `String` zurück, kein `Word`
> => "Aale"
> ```

Ich schlage vor, wir lösen das aktuell mit der Holzhammermethode:
`Word.all.each do |w|` und die Varianten in eine neues Array/Hash/WhatEver schreiben. Daraus dann die Liste erstellen. Ist natürlich ein Performance Alptraum, aber damit haben wir jetzt eine Lösung und können uns in der Zukunft Gedanken darüber machen, ob wir das optimieren oder nicht.

Mit einem Cache wäre das mit kleinem Aufwand optimierbar. Brauchen wir aber jetzt erst mal nicht. "Berühmte letzte Worte in der IT." 😂

**Comment by phortx** [comment]
Alles klar Chef, Holzammer kommt :D

**Comment by phylor** [comment]
Anstatt dem Cache ginge mittelfristig so etwas:

```sql
select x.* from words w cross join lateral (values
  (w.id, w.name),
  (w.id, w.plural)
  -- hier je eine Zeile für jede Spalte, die eine Wortvariante enthält, die im Index erscheinen soll
) as x(id, name) where (x.name = '') is not true;
```

Das ergibt dann:

```
  id  |            name
------+----------------------------
  700 | Bildungsplan
  847 | Etui
 1046 | Gymnasium
 1202 | Klassik
 1326 | Mädchen
 1453 | Paralympics
 1632 | Schild
 1797 | Strategie
 1991 | VR-Brille
 2063 | Zeichenblock
```

Mit [scenic](https://github.com/scenic-views/scenic) lässt sich daraus ganz einfach eine SQL View erstellen. Mit ActiveRecord lässt sich dann auch ein praktisches Model ableiten:

```ruby
class IndexWord < ApplicationRecord
  self.table_name = 'my_view_name'

  belongs_to :word, foreign_key: :id
end
```

Mit `IndexWord.all` hätten wir dann alle Wortvarianten.

**Comment by phortx** [comment]
Die Lösung von @phylor ist vermutlich die einzige, die wirklich funktioniert. Mit der Holzhammer-Methode bin ich zwar gerade schnell zu einem funktionierenden Ergebnis gekommen, dann aber in ein paar Fallen gelaufen. Z.B. dass die Wort-Varianten nicht zwangsläufig mit dem selben Buchstaben beginnen (sein/bin). Man müsste also immer ALLE Wörter aus der DB laden, das zu einem Array mit allen Varianten umbauen, dieses dann flatten, sortieren, filtern, paginieren usw. alles manuell. Das ist ziemlich aufwendig. Dann können wir auch direkt die saubere Lösung bauen, die Serge vorgeschlagen hat. Ich probiere das mal aus. 

Danke, @phylor für den guten Vorschlag!

**Comment by wintermeyer** [comment]
Vielleicht habe ich mich zu kompliziert ausgedrückt. Hier in Hau-Ruck-Code was ich meine (das Beispiel nur mal mit Singular und Plural):

`(Word.all.select(:slug, :name).map {|x| [x.name, x.slug]} + Word.where.not(plural: "").select(:slug, :plural).map {|x| [x.plural, x.slug]}).sort` 

In der Route die Buchstaben raussuchen und dann das eben generierten Array nach diesem Buchstaben rausfiltern. Das wäre eine Quick and Dirty Methode. Kann man noch um die anderen Daten erweitern.

PS: Mir ist klar, das das unnötig langsam ist. Es geht mir jetzt nur mal um die Funktionalität.

**Comment by phortx** [comment]
Ja, den Ansatz, den ich hatte war sogar noch einfacher (siehe aktuellen Stand des Branches), hat aber den Nachteil, dass ggf. Wörter unter dem falschen Buchstaben auftauchen. Deinen Ansatz wird ziemlich viel Code produzieren, aber ich probiere das mal möglichst sauber einzubauen. Danke für den Vorschlag :)

**Comment by wintermeyer** [comment]
Man kann auch direkt noch die Zusatzinformation mit einbauen:

`(Word.all.select(:slug, :name).map {|x| [x.name, x.slug, ""]} + Word.where.not(plural: "").select(:slug, :name, :plural).map {|x| [x.plural, x.slug, "Plural von #{x.name}"]}).sort`

Klar, kein schöner Code. Aber schnell zu realisieren und reicht für diesen Anwendungsfall.

Pro Buchstabe eine Seite. Keine Paginierung innerhalb eines Buchstabens. Keep it simple.

**Comment by phortx** [comment]
Habe das mehr oder weniger genau so nur etwas generischer und etwas eleganter eingebaut. Performance ist nicht ganz so mies, wie ich befürchtet habe (aber nicht optimal).

Sollen da bei den Nomen auch die unterschiedlichen Fälle rein?

Ansonsten muss ich nur noch die Übersetzungen ordentlich bauen.

**Comment by phortx** [comment]
i18n ist auch umgesetzt. 

Ich habe außerdem ein `.uniq` eingebaut, damit gleiche Worte nicht mehrfach gelistet werden (mir fällt gerade nur das englische put, put, put ein).

Bleiben nur noch die beiden Fragen nach den Fällen für Nomen und ob wir die Buchstaben-Navigation noch ändern wie gewünscht.

**Comment by phortx** [comment]
> Ja, wenn wir schon mal dabei sind.

Erledigt :)
