### ISSUE TITLE
Beispiel-Sätze für alle Wortarten

### ISSUE THREAD

**Issue by phortx** [wort-schule/wort.schule#186]
Aktuell werden die Beispielsätze nur für Nomen ausgegeben. Das soll aber auch für alle anderen Wortarten passieren. Hier müssen ggf. auch die Formulare entsprechend angepasst werden, wenn die Sätze dort auch fehlen.

**Comment by wintermeyer** [comment]
@all Wer zu erst kommt, mahlt zu erst.

**Comment by wintermeyer** [comment]
Ist zwar ein Bug, hat aber keine große Dringlichkeit.

**Comment by phortx** [comment]
Ich sehe mir das mal an :)

**Comment by phylor** [comment]
Implementiert in #183
