### ISSUE TITLE
Mobile Ansicht des Suchergebnis

### ISSUE THREAD

**Issue by wintermeyer** [wort-schule/wort.schule#187]
> 1.000 Worte:

<img width="390" alt="Bildschirm­foto 2023-02-25 um 17 19 31" src="https://user-images.githubusercontent.com/69770/221367837-d5e204f3-3bba-4f9a-9962-7cb6aea8413b.png">

- Der Suchfilter Button braucht etwas Padding rechts und links.
- Das mit den Ergebnissen passt im Mobilen View gar nicht. Da verbraten wir unnötig viel Real Estate. Aber da ist guter Rat teuer. @xamiam: Falls Du eine gute Idee dazu hast, wäre jetzt ein guter Zeitpunkt dafür. ;-) 
- Auf jeden Fall sollten wir schon mal Anstatt 7.938 eher 7K schreiben. In der heutigen Zeit ist bei unserem Zielpublikum klar, was es damit auf sich hat (Danke an TikTok und Co.). BTW: Bitte beim Desktop auch 7.938 und nicht 7938 schreiben. 
- Falls @xamiam keine bessere Idee hat, wäre mir immer noch lieber das ganze mit Komma abzutrennen. Also nicht als `<ul><li>` sondern als "7K Ergebnisse, 5K Substantive, 1K Verben, 946 Adjektive, 2 Funktionswörter". Nicht super toll, aber Real Estate ist limitiert und ich möchte above the fold to attraktiv wie möglich gestalten.

**Comment by phylor** [comment]
In #171 haben wir folgendes:

![image](https://user-images.githubusercontent.com/1394828/221368440-2495c3d0-4407-4350-b4bd-c2c87b23401e.png)

Die Dropdown ist technisch nicht ganz einfach umzusetzen, weil es nicht responsive ist. Wir müssten also für Mobile und Desktop die Worttypen separat implementieren - ist auch nicht ganz einfach weil wir die Formularfelder nicht duplizieren dürfen :slightly_smiling_face: 

Inwieweit setzen wir das Design um? Das heisst, die runden blauen Buttons z.B.?

**Comment by wintermeyer** [comment]
<img width="397" alt="Bildschirm­foto 2023-02-25 um 17 41 17" src="https://user-images.githubusercontent.com/69770/221368820-8609c748-f96b-4ca0-b41f-d705d0f5a232.png">

Das ist auf jeden Fall besser auf Mobile. 

> Die Dropdown ist technisch nicht ganz einfach umzusetzen, weil es nicht responsive ist. Wir müssten also für Mobile und Desktop die Worttypen separat implementieren

Das wäre jetzt mein Vorschlag gewesen.

> - ist auch nicht ganz einfach weil wir die Formularfelder nicht duplizieren dürfen 🙂

Das ist natürlich blöd. Ich wusste nicht, das das Formularfelder sind. Kann man das auch als Links machen? Über die URL ist das doch auch abbildbar, oder?

> Inwieweit setzen wir das Design um? Das heisst, die runden blauen Buttons z.B.?

Done is better than perfect. 

Das mit den runden blauen Buttons gefällt mir schon sehr gut, aber ist gerade nur sinnvoll, wenn Du dafür auch Zeit hast. Sonst machen wir das später.
