### ISSUE TITLE
Use TTS to generate audio output

### ISSUE THREAD

**Issue by cabotine** [wort-schule/wort.schule#19]
It would be cool (aka enhancement with extra money) to have an audio output for words and example sentences.

The mp3 files can come from WaveNet from Google: https://cloud.google.com/text-to-speech/#section-11 
It would be necessary to be able to create the mp3s and to select the options (like speed, voice, and so on).

**Comment by wintermeyer** [comment]
@phortx mentioned https://aws.amazon.com/de/polly/ as a possible alternative.

@cabotine What was the reason for using the Google TTS?

**Comment by wintermeyer** [comment]
> As a free/open alternative, there is [TTS by mozilla](https://github.com/mozilla/TTS) which is based on their [Common Voice](https://commonvoice.mozilla.org/en) project.

I am sceptical about this. I only found https://colab.research.google.com/drive/1SPl226SwzrfMZltrVagIXya_ax4CsMh-?usp=sharing for a German model and we don't have the resources or the knowhow to reinvent the TTS wheel. We need an API which does a good job out of the box.

**Comment by wintermeyer** [comment]
https://github.com/wort-schule/wort.schule/issues/68
