### ISSUE TITLE
Adding verbs, nouns and adjectives

### ISSUE THREAD

**Issue by cabotine** [wort-schule/wort.schule#201]
Hey,
due to the removable of the controllers for nouns/verbs/adjectives we also lost the possibility to add them or am I missing something?
Could you add the links to add them to the "Sonstiges" menu?
Thank you!

**Comment by phylor** [comment]
I haven't yet removed them. Here are the links:

- https://wort.schule/seite/nouns
- https://wort.schule/seite/verbs
- https://wort.schule/seite/adjectives
- https://wort.schule/seite/function_words

But yes, the "add" links need to go somewhere! Good catch. @wintermeyer

**Comment by cabotine** [comment]
Thank you!

**Comment by wintermeyer** [comment]
@phylor Please add it to "Sonstiges" page. For now.
