### ISSUE TITLE
Just one result? Go to word detail page directly (skip result page)

### ISSUE THREAD

**Issue by cabotine** [wort-schule/wort.schule#203]
If there is just one search result, because you entered the word properly it might make sense to go to the word detail page directly and skip the search result page with just one entry.

https://user-images.githubusercontent.com/8180537/221430945-88869be4-6eee-4801-bd14-c47a6b31494b.mp4

**Comment by wintermeyer** [comment]
First I thought: Yes, that is a very good improvement. 

But after a minute I thought:

- What about fuzzy search? Maybe somebody doesn't know how to spell a work and by coincidence there is an other word which fits.
- I prefer to have one workflow which always works the same. Easier to support. Easier to use for non-technical people. Especially for Grundschüler.
- Google has a "Auf gut Glück!" button with a similar functionality but the default works always by displaying a search result page.
