### ISSUE TITLE
Suche funktioniert nicht

### ISSUE THREAD

**Issue by wintermeyer** [wort-schule/wort.schule#204]
Man bekommt die Suchergebnisseite nicht angezeigt:

![ScreenFlow](https://user-images.githubusercontent.com/69770/221433233-ac323d7b-a55d-4412-a2e2-551a094172b2.gif)

**Comment by cabotine** [comment]
This works for me now on Windows and Android but not on the iPad (Safari).

**Comment by wintermeyer** [comment]
> This works for me now on Windows and Android but not on the iPad (Safari).

@cabotine Did you reload the page? I just want to make sure. It is working on my iPhone which uses the same browser as the iPad.

I just want to be 100% sure before reopening this issue.

**Comment by cabotine** [comment]
Yes. I did. Cannot find out the safari version though. Kind of annoying. "Ergebnisse zeigen" works but the blue arrow button does not.

**Comment by cabotine** [comment]
I can try to record a video later.

**Comment by wintermeyer** [comment]
> I can try to record a video later.

Finally a good reason for me to buy an iPad. I have been waiting for years for a good argument. ;-)
