### ISSUE TITLE
Ignore trailing spaces created by mobile keyboards

### ISSUE THREAD

**Issue by cabotine** [wort-schule/wort.schule#208]
Observing users showed me that people use the suggested word from a keyboard, which also adds a trailing space at the end of the word. This leads then to no search results. Maybe there is a function to remove trailing spaces?

https://user-images.githubusercontent.com/8180537/221527451-bc1aa0c5-8fbb-4bd0-bb69-2b7c982695e4.mp4

**Comment by wintermeyer** [comment]
Thanks for the feedback!

@all Is there a standard way to Theo the Devise not to use autocomplete? If yes we should do that. 

Anyhow we have to trim the search term.

**Comment by phylor** [comment]
> @ALL Is there a standard way to Theo the Devise not to use autocomplete? If yes we should do that.

We already disabled autocomplete (the one from the browser). I believe you are talking about the suggestions right above the keyboard? That is a feature from the keyboard and I wouldn't suggest to disable it as it's an accessibility feature for a lot of people.

**Comment by wintermeyer** [comment]
Then just a trim to remove white spaces.
