### ISSUE TITLE
Audio player is missing

### ISSUE THREAD

**Issue by cabotine** [wort-schule/wort.schule#218]
The audio player is gone for some reason. :(

![grafik](https://user-images.githubusercontent.com/8180537/221689750-e4d0b441-41ac-47f9-b523-f6f740631e44.png)

**Comment by phortx** [comment]
Is TTS enabled for this word?

**Comment by cabotine** [comment]
This happened for all words who had audios before (also Aal, Abenteuer etc.).

**Comment by phortx** [comment]
I think the audio generation job has to be triggered once again for each word with enabled tts, due to the changed data structure (has_one to has_many).

`Word.where(with_tts: true).each { |w|  TtsJob.perform_later(w) }` (or `perform_now` when there is no job runner).

@wintermeyer can you do this?

**Comment by wintermeyer** [comment]
> `Word.where(with_tts: true).each { |w| TtsJob.perform_later(w) }` (or `perform_now` when there is no job runner).
> 
> @wintermeyer can you do this?

Done. Auszug aus top. ;-)

```bash
    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     ZEIT+ BEFEHL
1553642 wortsch+  20   0 1038756 737832  33004 R 100,0   1,1   2:34.88 ruby
```

**Comment by wintermeyer** [comment]
I close this issue.

Test: https://wort.schule/aal

BTW: Hammer Beispielsatz! ;-)

**Comment by wintermeyer** [comment]
> `Word.where(with_tts: true).each { |w| TtsJob.perform_later(w) }` (or `perform_now` when there is no job runner).

@phortx Please add this code to the documentation.
