### ISSUE TITLE
Missing i18n on production

### ISSUE THREAD

**Issue by wintermeyer** [wort-schule/wort.schule#223]
https://wort.schule/seite/wort-index/a

<img width="1141" alt="Bildschirm­foto 2023-02-28 um 08 21 25" src="https://user-images.githubusercontent.com/69770/221782496-329a305f-e962-45d3-82b1-52b94a6971ce.png">

**Comment by cabotine** [comment]
[abartiger](https://wort.schule/abartig) translation missing: de.seo.word_index.fields.comparative von abartig

I have not checked all pages but I saw this.

**Comment by phortx** [comment]
Fixed in https://github.com/wort-schule/wort.schule/pull/227
