### ISSUE TITLE
Safari on ipad: spaces missing

### ISSUE THREAD

**Issue by cabotine** [wort-schule/wort.schule#224]
I am sorry, but I tried opening the app on the iPad our pupils use in school and there the spaces are missing here and there:
![C0C57365-C2FB-46B3-8A19-D80C9E15CC0E](https://user-images.githubusercontent.com/8180537/221782932-14991ae7-5997-4871-acc8-c2a72655018a.png)
![8327B106-69E8-4A6C-99B2-08391986167D](https://user-images.githubusercontent.com/8180537/221782938-087ec595-e7e0-431a-9845-b7922e7b7f92.png)

**Comment by wintermeyer** [comment]
It is a bug.

@phylor Please have a look. Here's the HTML:

```html
<div class="flex items-baseline gap-1">
<div class="text-xl">die</div>
<div class="text-xl font-bold">Liebe</div>
</div>
```

There is a space missing. It should be:

```html
<div class="flex items-baseline gap-1">
<div class="text-xl">die </div>
<div class="text-xl font-bold">Liebe</div>
</div>
```

**Comment by cabotine** [comment]
And also with the result overview (6 Ergebnisse
3 Substantive
2 Verben
1 Adjektive
0 Funktionswörter)

and in the list of results on the start page.

**Comment by wintermeyer** [comment]
> And also with the result overview (6 Ergebnisse 3 Substantive 2 Verben 1 Adjektive 0 Funktionswörter)

1.000 Wörter:

<img width="391" alt="Bildschirm­foto 2023-02-28 um 08 32 59" src="https://user-images.githubusercontent.com/69770/221784641-c2e15471-2cf6-4005-a8e0-24a3e0ff8a12.png">

Merkwürdigerweise habe ich das Problem bei mir nicht:

<img width="682" alt="Bildschirm­foto 2023-02-28 um 08 34 26" src="https://user-images.githubusercontent.com/69770/221784891-04a869f6-89b8-4ebc-b358-e8ac72616e22.png">

Wäre auch prinzipiell ein anderes Problem. Das wäre ein CSS Padding Problem. Bei dem Artikel ist es kein CSS Problem.

**Comment by phylor** [comment]
Oh ja, "ältere" iPads unterstützen die CSS Eigenschaft `gap` nicht. Die wird auch beim Artikel verwendet. Wir könnten uns dort zwar mit einem Leerzeichen behelfen, das hilft aber nicht bei allen anderen Verwendungen, wie z.B. den Suchresultaten.

Ich hoffe es gibt mittlerweile einen Polyfill dafür. Werde ich mir anschauen!

**Comment by wintermeyer** [comment]
> Oh ja, "ältere" iPads unterstützen die CSS Eigenschaft `gap` nicht.

Ich bin old school und kein großer Freund von so was. Rein logisch brauchen wir an der Stelle ein echtes Leerzeichen und kein `gap`.

> Ich hoffe es gibt mittlerweile einen Polyfill dafür. Werde ich mir anschauen!

Ich bin offen für gute Argumente, aber beim ursprünglichen Problem ("Liebe, die") sollte IMO ein echtes Leerzeichen rein. Beim zweiten Problem hast Du Recht. Das ist dann was für einen Polyfill work around.

**Comment by wintermeyer** [comment]
> Oh ja, "ältere" iPads unterstützen die CSS Eigenschaft `gap` nicht.

Wie ist "ältere" definiert?

Das ist ein ganz dünnes Drahtseil. Ich hatte schon Kundenprojekte, da hatten wir mehr Zeit damit verbracht "alte" Browser zu unterstützen, als neue Features einzubauen. Es ist schmerzhaft, aber irgendwann muss man den Schlussstrich ziehen. Wir leben in einer Welt der Evergreen Browser.

**Comment by phylor** [comment]
Ab April 2021 ist es ok:

![image](https://user-images.githubusercontent.com/1394828/221789595-7fa69217-63e5-4c89-a8b9-a2a248e83ba8.png)

https://caniuse.com/flexbox-gap

Also noch nicht soo alt - iPads sind ja auch recht langlebig.

**Comment by wintermeyer** [comment]
@cabotine Ist Dein iPad auf dem aktuellen Softwarestand? Kannst Du mal schauen, ob iOS geupdated ist? Interessiert mich mal. Welches iOS Version benutzt Du?

**Comment by wintermeyer** [comment]
@phylor 

- Nehmen wir mal an, wir benutzten ein Polyfill hier. Wie deaktivieren wir das wieder? Und wann? Ich habe Angst, das das in 5 Jahren noch drin sein wird, weil sich daran natürlich nie jemand erinnert.
- Kommt das Problem sonst noch irgendwo vor?

Prinzipiell: 
- "Liebe, die" ist mit einem Leerzeichen fixbar und das ist IMO auch der korrekte Weg. 
- Bei den Reitern: Im absoluten Notfall nehmen wir ein Polyfill. Mir wäre aber ein anderer Weg lieber. Im Zweifelsfall kann ich da sogar mit diesem Schönheitsproblem leben. Man kann alte Browser nicht beliebig lange unterstützen. Traurig aber war.

**Comment by cabotine** [comment]
iOS 14.4.1 hab ich hier. iPad (8. Generation). 100.000 Stück davon wurden während Corona an Schulen in Bremen (und vermutlich auch anderswo) angeschafft.

**Comment by cabotine** [comment]
Da fehlte wohl ein Haken für aktualisier Dich mal in Jamf. Ich aktualisiere es und schau dann nochmal.

**Comment by cabotine** [comment]
Unter iOS 16.3.1 funktioniert es erwartungsgemäß.

**Comment by wintermeyer** [comment]
@phylor Kannst Du das Leerzeichen hinter dem Artikel hinzufügen (das gap brauchen wir dann ja nicht mehr, oder?). Dann kann ich in ruhe schlafen. Ich habe immer Angst, das irgend ein Screenreader das nicht richtig versteht und das würde mich ärgern.

```html
<div class="flex items-baseline">
<div class="text-xl">die </div>
<div class="text-xl font-bold">Liebe</div>
</div>
```

Danach das Issue schliessen. Die anderen Sachen sind ja ok.
