### ISSUE TITLE
Beauty Fixes Wort Index

### ISSUE THREAD

**Issue by wintermeyer** [wort-schule/wort.schule#226]
Aktuell steht auf https://wort.schule/seite/wort-index/a folgendes:

<img width="319" alt="Bildschirm­foto 2023-02-28 um 09 36 59" src="https://user-images.githubusercontent.com/69770/221798420-5421fafc-84b0-4a5e-bb04-c9ad7cacb7fb.png">

HTML Beispiel Code dazu:
```html
<li>
<a href="/a-note">A-Note, der</a>
<span class="text-sm text-slate-500">Form des 2. Falls, Singular von A-Note</span>
</li>
```

Ich hätte gerne die zusätzliche Information in der Zeile unter dem Wort. Der Link sollte dann auch anders sein.

```html
<li>
<span class="text-slate-500">A-Note, der</span><br>
<span class="text-xs text-slate-500">Form des 2. Falls, Singular von </span><a href="/a-note" class="text-xs text-blue-600 dark:text-blue-500 hover:underline">A-Note</a>
</li>
```

<img width="272" alt="Bildschirm­foto 2023-02-28 um 09 49 50" src="https://user-images.githubusercontent.com/69770/221801409-101a1170-949d-4690-9880-9136a39b829a.png">

Bei mir wird der Link trotzdem nicht blau angezeigt. Vielleicht kann das jemand fixen.

Zusätzlich würde ich auch gerne `<ul class="list-disc">` benutzen. Wird bei mir aber auch nicht angezeigt. Any ideas why?

Wenn es sich um den Haupteintrag handelt, dann muss der Link natürlich auch anders sein (sprich direkt).

**Comment by phortx** [comment]
Es ist an der Stelle nicht ganz trivial zu unterscheiden ob das ein Haupteintrag ist. Ich baue aber dennoch mal ein Vorschlag, der dem etwa entspricht. Der Link geht sowieso immer zum Basis-Wort, weil die Formen, Fälle etc. ja keine eigenen Seiten haben.

**Comment by wintermeyer** [comment]
Gefällt mir. Macht Sinn. 👍

**Comment by phortx** [comment]
Sorry, MR kommt. War die letzten Tage im Urlaub :)
