### ISSUE TITLE
Audio Player erscheint erst nach einem Reload

### ISSUE THREAD

**Issue by wintermeyer** [wort-schule/wort.schule#228]
Ich suche ein Wort und bekomme beim ersten Anzeigen der Wort#show Seite den Audio-Player nicht angezeigt. Erst nach einem Reload. Fühlt sich an wie ein Caching- oder Turbolinks-Problem an. Manchmal klappt es, manchmal nicht.

![audio-reload](https://user-images.githubusercontent.com/69770/222124982-8092948e-1e4d-458e-af9b-92fdafa6b729.gif)

Ich nehme mal @phortx und @phylor ins Boot, weil ich mir jetzt gar nicht sicher bin, in wessen Spielfeld der Ball sich bei diesem Problem befindet.

**Comment by cabotine** [comment]
Auf Windows (Firefox und Chrome) tauchen die Audioausgaben übrigens korrekt auf. Android (Firefox, Chrome) auch.

**Comment by wintermeyer** [comment]
Tatsächlich. Ist ein Safari Problem. Auch Chrome (macOS) funktioniert es.

**Comment by cabotine** [comment]
Auf dem iPad besteht das Problem tatsächlich auch.

**Comment by phortx** [comment]
Ich habe leider kein Gerät zum Testen. Was man mal probieren kann:
- Absolute URL in der source angeben
- Mal debuggen ob das Element vorhanden aber nur nicht sichtbar ist, ggf. min-width setzen

**Comment by wintermeyer** [comment]
An der Stelle ist tatsächlich ein Audioplayer. Er wird nur nicht beim ersten Laden angezeigt.

![unsichtbarer_audioplayer](https://user-images.githubusercontent.com/69770/222441938-575e984d-1e28-415b-b340-068495563bde.gif)

**Comment by wintermeyer** [comment]
AFAIK sollte das gefixt sein.

**Comment by wintermeyer** [comment]
@phylor Hast Du eine Idee?
