### ISSUE TITLE
die Schule (Delfine)

### ISSUE THREAD

**Issue by wintermeyer** [wort-schule/wort.schule#245]
Entweder ist das ein Import, der schief gelaufen ist oder ein Mensch hat das System nicht verstanden. Wörter mit Beschreibungen in Klammern dahinter machen keinen Sinn.

https://wort.schule/schule-delfine

**Comment by cabotine** [comment]
Ja. Es gibt auch ein paar Wörter mit händisch eingetragenen Artikeln. Wir
kümmern uns drum.


Stefan Wintermeyer ***@***.***> schrieb am Fr., 3. März 2023,
07:39:

**Comment by wintermeyer** [comment]
@cabotine Kannst Du das Issue schliessen (Close)? Ich bin mir mit den Rechten nicht so sicher.
