### ISSUE TITLE
Automatisches Auslösen der Suche beim Aufruf von https://wort.schule

### ISSUE THREAD

**Issue by wintermeyer** [wort-schule/wort.schule#246]
Wenn ich https://wort.schule aufrufe, dann wird direkt die Suchergebnisliste gestartet. Nur wenn ich mit einem privaten Browserfenster https://wort.schule aufrufe (sprich keine Cookies gesetzt sind) bekomme ich die normale Funktionalität.

![bug](https://user-images.githubusercontent.com/69770/222655882-d0c8054b-32f2-496f-913b-f2282581242c.gif)

Browser: Safari macOS

**Comment by phylor** [comment]
Bist Du dir sicher, dass Safari wirklich `https://wort.schule` aufruft? Oder könnte es sein, dass Safari die letzte URL dieser Domain aufruft? Ist das Verhalten identisch wenn Du explizit `https://wort.schule/` eingibst (inkl. `https` und dem `/` zum Schluss) und die ganze Domain ausschreibst, d.h. das Autocomplete nicht nutzt?

Ich kann mir das Verhalten nicht erklären. Falls es nicht am Autocomplete von Safari liegt, wäre spannend zu sehen welche Netzwerk Requests gemacht werden. Falls Du dies in den Entwicklungstools oder einem Proxy siehst?

**Comment by wintermeyer** [comment]
Tja, ... ich bin ein wenig ratlos. Ich kann das Problem nicht sicher reproduzieren, habe es aber immer mal wieder. Eine ganz wilde Theorie dazu: Kann es sein, das das Enter, das ich nach der URL Eingabe drücke, an den Eingabebutton weitergegeben wird? So eine Art Race-Condition, weil der Browser die Seite vielleicht schon vorher automatisch fetched.

Wäre es viel Aufwand diesen Button erst benutzbar zu machen, wenn mindestens ein Zeichen im Eingabefeld ist? Ich habe es gerade bei Google ausprobiert und dort funktioniert es genau so.
