### ISSUE TITLE
Up- and Down plus Enter leads to "content missing"

### ISSUE THREAD

**Issue by wintermeyer** [wort-schule/wort.schule#257]
After entering "auto" I use the arrow keys to go to "das Auto" hit Enter and get a "content missing".

![arrow-key-bug](https://user-images.githubusercontent.com/69770/223339923-34356655-ba82-4402-9850-3fa0ae3341b9.gif)

**Comment by cabotine** [comment]
Also clicking with the mouse on results leads to content missing.

**Comment by phylor** [comment]
@wintermeyer 

1. Klick mit der Maus auf ein Suchresultat funktioniert jetzt aber, korrekt?
2. Mit Enter lädt es bei mir auf Produktion nun manchmal das Suchresultat, manchmal passiert gar nichts. Ist das bei dir auch so? Oder siehst du noch immer `Content missing`?

**Comment by wintermeyer** [comment]
> 1. Klick mit der Maus auf ein Suchresultat funktioniert jetzt aber, korrekt?

Korrekt.

> 2. Mit Enter lädt es bei mir auf Produktion nun manchmal das Suchresultat, manchmal passiert gar nichts. Ist das bei dir auch so? Oder siehst du noch immer `Content missing`?

Ich sehe kein `Content missing` mehr. Es passiert nichts. Merkwürdigerweise verändert sich aber die URL im Browser.

Beispiel:

https://wort.schule/?filterrific%5Bfilter_home%5D=bus&button=

<img width="1156" alt="Bildschirm­foto 2023-03-07 um 18 45 28" src="https://user-images.githubusercontent.com/69770/223505560-5cd68f8d-2fe3-4e32-b7ac-4f7c55ce27d4.png">

**Comment by phylor** [comment]
Funktioniert bei mir jetzt auf Produktion. Schliesse das Issue. Bitte melden falls es doch noch auftritt!
