### ISSUE TITLE
Add #show for function words

### ISSUE THREAD

**Issue by cabotine** [wort-schule/wort.schule#26]
At the moment function words can be found with the advance search, but they don't have a details page yet.
Example "das"

**Comment by wintermeyer** [comment]
![suchen-das](https://user-images.githubusercontent.com/69770/201112041-7eb840b4-5ff6-42f8-896d-182cb94c77a9.gif)

**Comment by cabotine** [comment]
Funktionswörter

**Comment by wintermeyer** [comment]
# Tasks

- [ ] Fix that #show page works (e.g. https://wort.schule/das)
- [ ] Add a Wortart category to the big search for "Funktionswörter"

**Comment by phylor** [comment]
There already is a detail page for function words:

![image](https://user-images.githubusercontent.com/1394828/201304059-2231067e-60fe-4831-96da-3372929efa2f.png)

It was a bit unintentional that they appear in the search. :slightly_smiling_face: We need to link to them from the search results and add the category as a search option (as already in the task list - I'll add the search result link).

I also noticed that function words are not accessible by guest users and students (this is why https://wort.schule/das does "not work"). @wintermeyer Is it correct that everybody should be able to look at function words? If so, we should add `can :read, FunctionWord`.

**Comment by wintermeyer** [comment]
> @wintermeyer Is it correct that everybody should be able to look at function words? If so, we should add can :read, FunctionWord.

Yes and yes.
