### ISSUE TITLE
301 redirect /Haus to /haus

### ISSUE THREAD

**Issue by wintermeyer** [wort-schule/wort.schule#27]
In case a user opens https://wort.schule/Polizei (with any number of capital letters) the system redirects the request with a 301 error code to https://wort.schule/polizei

**Comment by phylor** [comment]
As a hunch: we should `downcase` the `word` in `app/services/slug_constraint.rb`. That should make it case insensitive.

It wouldn't redirect to the "proper" URL though. That would require a bit more logic in the controllers.

**Comment by wintermeyer** [comment]
> It wouldn't redirect to the "proper" URL though. That would require a bit more logic in the controllers.

We have to do a proper 301 redirect here. If somebody opens https://wort.schule/Adler I don't want him/her to get the adler page I don't want the user to bookmark that page and I don't want a potential search engine to crawl it either. I want the system to redirect it to https://wort.schule/adler with a proper 301 HTTP redirect. THAT page can be bookmarked and that page can be crawled by search engines.
