### ISSUE TITLE
Pull-Down disabled wenn kein Inhalt

### ISSUE THREAD

**Issue by wintermeyer** [wort-schule/wort.schule#272]
@phylor Kannst Du solche Formularelemente mit wenig Aufwand disablen? Also, wenn sie keinen Inhalt haben. Erst dachte ich ganz von der GUI entfernen, aber disabled/ausgrauen ist besser. Dann verändern sich die Positionen innerhalb der GUI nicht.

![ScreenFlow](https://user-images.githubusercontent.com/69770/224932423-d0b4f0d3-fd23-4b5e-8b85-6230f8b1dc2e.gif)

Beispiel-URL:
https://wort.schule/seite/search?filterrific%5Bfilter_home%5D=polizei&is_filter_open=true

**Comment by phortx** [comment]
Ich sehe mir das an :)

**Comment by wintermeyer** [comment]
@phortx Sorry, ich habe den falschen Account genommen. Das macht ja viel mehr Sinn, wenn @phylor sich das anschaut.

**Comment by phortx** [comment]
Alles klar :)
