### ISSUE TITLE
Link zur erweiterten Suche mit Filtern

### ISSUE THREAD

**Issue by wintermeyer** [wort-schule/wort.schule#273]
@xamiam Können wir sinnvoll auf / einen Link zu einer Erweiterten Suche mit Suchfiltern unterbringen oder hast Du eine andere Idee dazu? Ich will die / Seite so einfach und sauber wie möglich halten.

**Comment by xamiam** [comment]
Das hier wäre die einfachste Variante:

![grafik](https://user-images.githubusercontent.com/309421/225665521-d6e95817-914d-4cbb-a392-808fc75f4e3f.png)

**Comment by xamiam** [comment]
👍 

wie wär's dann hiermit?

![grafik](https://user-images.githubusercontent.com/309421/225914826-402483b5-131f-4414-8446-885e17308a08.png)

**Comment by wintermeyer** [comment]
Eher nicht (ich will das oben ganz einfach lassen). Ich glaube "Detailsuche" ist auch ein suboptimaler Begriff. "Filter" sind besser. Wie wäre es mit einem Link (also keinen Button) unter dem Suchen Button? Also unter dem Eingabefeld rechtsbündig.

**Comment by xamiam** [comment]
Wenn man die Suchfilter nur zulassen will, wenn bereits eine Eingabe erfolgt ist, kann man das auch wie folgt machen:

![grafik](https://user-images.githubusercontent.com/309421/225943284-093eb40a-2982-4202-96d6-34233cd4d3bd.png)

**Comment by wintermeyer** [comment]
> "Detailsuche" ist an der Stelle übrigens nicht unbedingt verkehrt. "Filter" ist imho eher ein technischer Begriff, der für Kinder u.U. nicht so gut verständlich ist.

Der Link ist eher für Lehrer gedacht.

**Comment by wintermeyer** [comment]
> Ich glaube, es braucht hier einen Button. Es macht Sinn, dass das Formular mit den bisherigen Eingaben abgeschickt wird, nur mit einem Flag für das Anzeigen der Filter auf der Suchergebnisseite.

Der Button ist mir hier zu thirsty. 99,99% aller User werden das hier nicht benutzen. Wir brauchen nur für die Lehrer, die auf dieser Seite sind einen Link, der direkt auf die Filtersuche ohne einen Suchbegriff führt.

**Comment by cabotine** [comment]
"Erweiterte Suche"? Find ich als Bezeichnung eigentlich gut. Ihn nur anzuzeigen, wenn man schon einen Buchstaben eingegeben hat, reicht meines Erachtens nicht aus, da es dann beim Aufmachen der Seite nicht sichtbar ist. (So selten wird die bestimmt nicht benutzt, zumindest wenn man sie finden kann.)

**Comment by wintermeyer** [comment]
> Das hier wäre die einfachste Variante:
> 
> ![grafik](https://user-images.githubusercontent.com/309421/225665521-d6e95817-914d-4cbb-a392-808fc75f4e3f.png)

@phylor Bitte mache es so. Das erscheint mir das kleinste Übel von allen zu sein. Aber mit einer Lupe als Icon und "Erweiterte Suche" als Text.

**Comment by cabotine** [comment]
Bei der erweiterten Suche müssten bitte auch die Filter sichtbar sein:
![grafik](https://user-images.githubusercontent.com/8180537/226855955-0641b64d-defc-4f99-8a78-ef1f986f6a5a.png)

**Comment by wintermeyer** [comment]
> Bei der erweiterten Suche müssten bitte auch die Filter sichtbar sein:

Da hast Du Recht! https://github.com/wort-schule/wort.schule/issues/290
