### ISSUE TITLE
Footer ändern

### ISSUE THREAD

**Issue by wintermeyer** [wort-schule/wort.schule#275]
Der aktuelle Footer ist mir zu laut. Gerade auf der Index Seite nehmen sich die Logos zu viel Aufmerksamkeit. Das ist auch alles etwas unaufgeräumt. Lenkt vom Hauptgeschehen ab. @xamiam hat eine Variante entworfen sie das Problem abmildert:

![desktop start](https://user-images.githubusercontent.com/69770/225852431-32e10be5-d2ae-45f3-9aa5-3394960a2adb.png)

- Wenn man mit der Maus über die einzelnen Logos rübergeht, dann sollten diese jeweils farbig erscheinen.
- Innerhalb der drei Logos gibt es eine imaginäre Linie (siehe Kopf der Schrift im Vergleich zu den anderen Logos). Die muss nicht pixelgenau eingehalten werden. Was immer mit normalem Aufwand möglich ist.
- Auf dem Screenshot fehlen ein paar Einträge. Da muss [Impressum](https://wort.schule/seite/impressum), [Quellcode auf GitHub](https://github.com/wort-schule/wort.schule), [Wiki](https://github.com/wort-schule/wort.schule/wiki), [Inhaltlichen Fehler melden](mailto:inhalt@wort.schule?subject=wort.schule%20Fehler%20oder%20Optimierung%20melden&body=Guten%20Tag,%0D%0A%0D%0Azur%20Webseite%20https://wort.schule/%20m%C3%B6chte%20ich%20folgenden%20Fehler%20melden:), [Technischen Fehler melden](https://github.com/wort-schule/wort.schule/issues/new), [Wort Index](https://wort.schule/seite/wort-index/a)" rein.

**Comment by xamiam** [comment]
Moin, 

Ein paar von den Einträgen habe ich absichtlich reduziert. Für den Quellcode muss man "Github" nicht nennen, die Fehlermeldungen kann man ggf. zusammenfassen bzw. über eine Verteilerseite laufen lassen, etc.

**Comment by phylor** [comment]
Jetzt sieht's so aus:

![screengrab-20230317-1532](https://user-images.githubusercontent.com/1394828/225934423-2899017c-8428-41b9-9e04-4b90d49fa788.gif)

Lasst mich wissen was wir mit den Links machen :slightly_smiling_face:
