### ISSUE TITLE
Neues Design der word#show Seite

### ISSUE THREAD

**Issue by wintermeyer** [wort-schule/wort.schule#276]
Hier das neue Design für https://wort.schule/ameisenbaer

Wie immer: Es sollte mit TailwindCSS Bordmitteln realisiert werden. Wenn das etwas anders aussieht, dann ist das so. Mit dem Framework arbeiten und nicht gegen einzelne Pixels. Im Zweifelsfall im Issue fragen/diskutieren. Der erste Screenshot ist für den Desktop. Der zweite für die Mobile Ansicht. iPad und Co. müssen wir uns dann mal im nächsten Schritt anschauen.

![detail desktop v2](https://user-images.githubusercontent.com/69770/225854137-86633282-ff58-4257-a867-719538747eef.png)

![detail mobile](https://user-images.githubusercontent.com/69770/225854149-457ccd71-903a-440e-b514-7800425947e7.png)

## Sonstiges

- Wir haben noch keine perfekte Idee für die Silbenbögen. Ich glaube die kann man mit CSS Bordmitteln "leicht" realisieren. Im Zweifelsfall aber erst mal weglassen und dafür ein extra Issue anlegen (mir zuweisen). 
- Wenn ein Panel leer ist, dann auch nicht anzeigen. Beispiel: Weitere Bedeutungen. https://wort.schule/bauer hat weitere Bedeutungen. Andere Wörter nicht. Bei letzteren braucht man das Panel nicht anzeigen.
- Ich glaube [Grid](https://tailwindcss.com/docs/grid-template-columns) ist der beste Weg für die Panels. Aber da bin ich mir nicht 100%ig sicher. 
- Den Audioplayer so lassen wie er jetzt ist. Sprich: Kein extra JavaScript Client nur für den Audio-Player einbauen.

**Comment by phylor** [comment]
@wintermeyer In den Designs von Desktop und Mobile ist die Reihenfolge der Panels unterschiedlich.

Ist das so gewollt? Oder können wir auf Mobile die folgende Desktop Reihenfolge verwenden?

![image](https://user-images.githubusercontent.com/1394828/225936353-681dcbde-a3cd-4484-a31c-bd98c53c8b89.png)

**Comment by phylor** [comment]
Wenn's dann mal wirklich drauf ankommt, können wir auch mit `grid-template-areas` die einzelnen Blöcke auf Mobile und Desktop in unterschiedlicher Reihenfolge darstellen. Das wäre aber unnötige Komplexität wenn es nicht wirklich gewollt ist.

**Comment by cabotine** [comment]
Cool!

Bedeutung gibt es kurz und lang in der Datenbank.

Die weiteren Bedeutungen sollten ggf. verlinkt sein (falls es welche gibt) oder unter der Bedeutungsbox kommen. Und vielleicht mit "Weitere Bedeutungen des Wortes" überschrieben sein?

Die Eigenschaften würde ich weiter nach unten sortieren. Die Wortsymbole dafür nach oben. Vielleicht die beiden einfach tauschen.

Soll ich über die Reihenfolge noch mal mit der Deutschdidaktikerin sprechen?

Es fehlt noch die Farbkodierung für das Geschlecht (farbiger Kreis in blau, rot oder grün vor dem Artikel). Kann aber auch später noch, wollte es nur schon gesagt haben. ;)

**Comment by wintermeyer** [comment]
> Die Eigenschaften würde ich weiter nach unten sortieren. Die Wortsymbole dafür nach oben. Vielleicht die beiden einfach tauschen.

👍

> Soll ich über die Reihenfolge noch mal mit der Deutschdidaktikerin sprechen?

Das kann nicht schaden. Aber warte bitte bis die neue Variante fertig ist. Das umsortieren ist kein Problem. Es wird aber der entsprechenden Person helfen, das prinzipielle Layout schon mal vor Augen zu haben.

> Es fehlt noch die Farbkodierung für das Geschlecht (farbiger Kreis in blau, rot oder grün vor dem Artikel). Kann aber auch später noch, wollte es nur schon gesagt haben. ;)

@xamiam Bitte schaue dir das mal an und mache dazu einen Vorschlag. Was weg ist, ist weg.
@phylor Mache ruhig an hand der jetzigen Informationen weiter. Ich kann mir nicht vorstellen, das diese farbigen Kreise alles durch einander schmeissen (famous last words).

**Comment by xamiam** [comment]
Prinzipiell finde ich grid für die Darstellung gut (gerne minmax für eine einfache responsive Anpassung) - damit bleibt die Zeilenausrichtung erhalten.
Wenn die Reihenfolge von Desktop zu mobile abweicht, ist xs:hidden etc. ggf. einfacher zu implementieren als das separat per CSS zu lösen.

Die Layoutvorlage ist eine ideale Darstellung - die Blöcke können im Einzelfall durchaus in der Höhe abweichen.

**Comment by wintermeyer** [comment]
> @wintermeyer Bleibt die Bearbeitungs-Ansicht vorerst so wie sie jetzt ist?

Ja.

**Comment by wintermeyer** [comment]
Ich habe ein neues Issue hierzu aufgemacht. https://github.com/wort-schule/wort.schule/issues/298
