### ISSUE TITLE
100% Treffer muss an erster Stelle gelistet sein

### ISSUE THREAD

**Issue by wintermeyer** [wort-schule/wort.schule#277]
Wenn auf der Index-Seite ein Suchbegriff einen 100%ig Treffer hat, dann muss dieser oder diese auch an erster Stelle im schnellen Zugriff haben. Beispiel "polizei". Hier muss "Polizei" vor "Polizeiauto" gelistet sein.

<img width="1312" alt="Bildschirm­foto 2023-03-16 um 11 11 01" src="https://user-images.githubusercontent.com/69770/225859576-81931d49-fa09-492d-ba4e-c9f7bdf16a61.png">

Weiteres Test-Beispiel:

<img width="1312" alt="Bildschirm­foto 2023-03-16 um 11 11 24" src="https://user-images.githubusercontent.com/69770/225860383-9fb4a480-7408-4367-be55-88146cceb733.png">

## Sonstiges

Eigentlich müsste "Polizei" auch schon bei "poliz" als erstes einsortiert sein. Rein von der menschlichen Logik. 

@phylor Kannst Du mir das Problem kurz erklären? Eigentlich müsste die alphabetische Sortierung doch "polizei" eh vor "polizeiauto" sortieren oder nicht?

**Comment by phylor** [comment]
@wintermeyer Scheinbar ist suchen sehr kompliziert :slightly_smiling_face: 

Der aktuelle Such-Query ist wie folgt:

```ruby
      Word.where(id:
        Word.union(
          filter_wordquery("#{query}%").select("*, 1 as weight"),
          filter_wordquery("%#{query}%").select("*, 2 as weight"),
          where("plural ILIKE ?", term).select("*, 3 as weight"),
          where("comparative ILIKE ?", term).select("*, 3 as weight"),
          where("superlative ILIKE ?", term).select("*, 3 as weight")
        ).order(:weight).pluck(:id))
```

Wir machen einzelne Suchen, zuerst nach `polizei%`, dann nach `%polizei%`, dann suchen wir in der Pluralform, usw. Jede dieser Suchen erhält ein Gewicht (1, 2, 3) nach denen wir sortieren.

Soweit die Theorie. Leider entfernt das äussere `where(id: ..)` die Sortierung wieder. Diesen äusseren Query braucht es um die Wörter zu ent-duplizieren. Das `UNION` von SQL kann in unserem Fall die Wörter nicht einzigartig zurückgeben, weil wir noch das Gewicht im Query haben. Als Resultate haben wir z.B. Polizei mit Gewicht `1` und Polizei mit Gewicht `2`. Die sind für SQL nicht eindeutig. Ich stelle gleich einen PR um dieses Problem zu beheben.

In deinem `polizei` Beispiel ist das Problem aber ein anderes. `polizei`, `polizeiauto` und `polizeihund` matchen alle gegen `query%`. Innerhalb dieses Queries haben wir keine Sortierung. Deshalb ist die Reihenfolge zufällig. Wir können hier alphabetisch sortieren, aber nur nach der Grundform des Worts. Wenn wir also in der Pluralform matchen, können wir nicht nach dieser sortieren. Wobei wir diese übrigens in den Resultaten gar nicht anzeigen (sondern nur die Grundform des Wortes).

**Comment by cabotine** [comment]
Bei der Suche nach Kinder passiert dann leider das... (ich weiß man bekommt nicht alles perfekt hin. Aber wenn eine 100% Übereinstimmung mit dem Plural zum Singular führen würde, wäre es cool...
![grafik](https://user-images.githubusercontent.com/8180537/226423030-b4217462-2087-4e3c-90dc-41803b15451e.png)

**Comment by wintermeyer** [comment]
@phylor Ich verstehe @cabotine. Das Grundproblem ist IMO ein Datenstrukturproblem. Das bekommen wir nicht auf die Schnelle gelöst. Aber wir können mit einer komplexeren Query ein besseres Ergebnis bekommen. 

Aktueller Code: 

```
      ids = Word.union(
         filter_wordquery(query).select("*, 1 as weight"),
         filter_wordquery("#{query}%").select("*, 2 as weight"),
         filter_wordquery("%#{query}%").select("*, 3 as weight"),
         where("plural ILIKE ?", term).select("*, 4 as weight"),
         where("comparative ILIKE ?", term).select("*, 4 as weight"),
         where("superlative ILIKE ?", term).select("*, 4 as weight")
       ).order(:weight, :name).ids.uniq
```

Wir müssen "nur" folgenden Pseudo Code hinzufügen:

```
where("plural ILIKE ?", query).select("*, 1 as weight"),
where("plural ILIKE ?", "#{query}%").select("*, 2 as weight"),
where("comparative ILIKE ?", query).select("*, 1 as weight"),
where("comparative ILIKE ?", "#{query}%").select("*, 2 as weight"),
where("superlative ILIKE ?", query).select("*, 1 as weight"),
where("superlative ILIKE ?", "#{query}%").select("*, 2 as weight"),
```

Ich nehme an, das Du schon entsprechende Indexes gesetzt hast. Die Lösung ist kein Traum an Normalisierung und Geschwindigkeit, aber wird das ganze schülerfreundlicher machen.

@phylor Bitte baue das ein. Bin mir nicht sicher, ob wir dafür ein neues Issue brauchen oder ob das hier noch mit reinkann/soll.
