### ISSUE TITLE
Creating a new user as admin crashes

### ISSUE THREAD

**Issue by cabotine** [wort-schule/wort.schule#28]
I tried to create a new user with admin rights and the site crashed (
We're sorry, but something went wrong.

If you are the application owner check the logs for more information.)

**Comment by wintermeyer** [comment]
@cabotine Do you have the possibility to screen record what you did and post a GIF export here? The whole browser window. Bonus points: Please include the exact time of this. Than we can look it up in the log files.

**Comment by wintermeyer** [comment]
@cabotine Please - for the sake of my health - don't use the word "crash" in this context. 😱 For a second I thought that the whole web server is down. But this is just an error page. Everything else works fine. 😉

**Comment by cabotine** [comment]
I am sorry. Will keep it in mind.
The account where it happend was "Weinhold". Do you have a good screen recorder with gif export for Windows?
It is supposed to send an email with a passwort? This seems not the case.

**Comment by phylor** [comment]
@cabotine Yes, it should send an email with a password recovery link.

Has the user been created though? That is, if you check the list of all users, the new user is present?

If it is, the error could be a problem with sending out emails. That is, the user was created, but then email could not be sent, resulting in the error.

It works fine for me locally. So the next step would be to check the logs, maybe searching for `POST "/users"`.

**Comment by cabotine** [comment]
Yes, it was created, but no email was sent.

**Comment by phylor** [comment]
@wintermeyer Just realized that we never changed the mail configuration. Could you check the configuration in `config/environments/production.rb`.

IMHO it would make most sense to replace it with environment variables, so that every deployment is able to easily change the mail server settings without the need of changing the code.

Unfortunately Rails doesn't provide env variables (unlike `$DATABASE_URL`), so we'd need to replace them on our own:

```
  config.action_mailer.default_url_options = {host: ENV["HOST"]}
  config.action_mailer.delivery_method = :smtp
  config.action_mailer.smtp_settings = {
    address: ENV["SMTP_HOST"],
    port: ENV["SMTP_PORT"],
    tls: ENV["SMTP_TLS"],
    enable_starttls_auto: ENV["SMTP_ENABLE_STARTTLS_AUTO"],
    openssl_verify_mode: ENV["SMTP_OPENSSL_VERIFY_MODE"]
  }
```

**Comment by wintermeyer** [comment]
closed by https://github.com/wort-schule/wort.schule/pull/43
