### ISSUE TITLE
Suchresultate | Hit anstatt Grundform anzeigen

### ISSUE THREAD

**Issue by phylor** [wort-schule/wort.schule#289]
> @phylor Can we display "Kinder" as the result and not "Kind"? My bad. Sorry for the overtime. Ideally it would be "Kinder (Plural von Kind)".

**Comment by wintermeyer** [comment]
Even better: “die Kinder (Plural von das Kind)“

**Comment by wintermeyer** [comment]
BTW: That would make our solution so much better than the duden.de search.

<img width="1285" alt="Bildschirm­foto 2023-03-22 um 07 30 56" src="https://user-images.githubusercontent.com/69770/226820705-84f893d5-2091-4b5f-8d8c-2cb61002b10d.png">

**Comment by cabotine** [comment]
Sehr cool auf der Suchseite!
Bei der Ergebnisseite kann es dann verwirrend sein.
![grafik](https://user-images.githubusercontent.com/8180537/230610552-78075429-b7d0-44d9-8d7a-d3c14b8b0837.png)

Ich kläre das mal mit Lehrkräften und Didaktiker:innen, ob eher Plural/Singular oder Einzahl/Mehrzahl bzw. Komparativ/Superlativ oder eher Steigerungsform (Komparativ).

**Comment by wintermeyer** [comment]
> Sehr cool auf der Suchseite! Bei der Ergebnisseite kann es dann verwirrend sein.

Ja, da ist noch room for improvement.

Die Wortbedeutung ist auch oft sehr verlassen, weil leer. Damit bin ich noch nicht richtig glücklich.

@xamiam Hast Du eine Idee, wie wir das besser lösen können? @cabotine will die Wortbedeutung drin haben. Aber faktisch haben die meisten Datensätze da gar keinen Inhalt. Vielleicht können wir die Wortart (die haben wir immer) und die Wortbedeutung irgendwie sinnvoll anzeigen.

Wir brauchen auch eine Lösung für den obigen Screenshot. Das "gut" angezeigt wird, macht ja sinn, aber es ist nicht klar, warum. Vielleicht könnten wir das auch irgendwie gelb untermalen. @xamiam kannst Du dazu mal einen Vorschlag erarbeiten?

> Ich kläre das mal mit Lehrkräften und Didaktiker:innen, ob eher Plural/Singular oder Einzahl/Mehrzahl bzw. Komparativ/Superlativ oder eher Steigerungsform (Komparativ).

@cabotine Vielleicht sollten wir bei solchen Sachen auch eine gemeinsame Videokonferenz mit diesen Fachleuten machen. Lehrkräfte und Didaktiker haben ja keine Idee, wie so eine GUI funktioniert und was möglich und was eher schwer möglich ist.
