### ISSUE TITLE
Neues visible (boolean) Attribute zu Quellen

### ISSUE THREAD

**Issue by cabotine** [wort-schule/wort.schule#291]
Es gibt unterschiedliche Arten von Quellen.
Solche die sichtbar sein sollen nach außen (die offiziellen Wortschätze der Länder) und andere, die nach außen nicht sichtbar sein sollen (Studisammlung XY).

![grafik](https://user-images.githubusercontent.com/8180537/226944990-cc6d26ae-7c45-4214-99fc-0bac71c60357.png)

**Comment by wintermeyer** [comment]
Der Default für `visible` sollte `true` sein. Bei der erweiterten Suche sollten dann die `false` Einträge nicht aufgelistet werden.

**Comment by phylor** [comment]
@wintermeyer Ich glaube ich hatte vergessen das Hinzufügen und Löschen von Wörtern zu einer Quelle zu implementieren. Brauchen wir das noch?

**Comment by wintermeyer** [comment]
> @wintermeyer Ich glaube ich hatte vergessen das Hinzufügen und Löschen von Wörtern zu einer Quelle zu implementieren. Brauchen wir das noch?

Gerade nicht. Können wir später immer noch machen.

**Comment by cabotine** [comment]
Das Hinzufügen/Löschen ist vermutlich sinnvoll beim Import mit zu erschlagen, oder?

**Comment by wintermeyer** [comment]
> Das Hinzufügen/Löschen ist vermutlich sinnvoll beim Import mit zu erschlagen, oder?

?

**Comment by cabotine** [comment]
Naja, ein typisches Szenario ist ja, dass man gerne einen Wortschatz ergänzen möchte (z.B. den eines Bundeslandes). Dafür ist es nicht praktikabel 500 Wörter per Hand rauszusuchen und zuzuordnen sondern eher eine Liste mit Wörtern und der Quelle zu importieren. Da sowieso die Importfrage noch zu klären ist, können wir da auch die Quelle als ein Feld mit hinzufügen.

**Comment by wintermeyer** [comment]
Ja, das würden wir bei einer Import Methode mit erschlagen.
