### ISSUE TITLE
502 Bad Gateway 

### ISSUE THREAD

**Issue by cabotine** [wort-schule/wort.schule#297]
Ich bekomme immer mal einen 502 Bad Gateway
![grafik](https://user-images.githubusercontent.com/8180537/227288625-7183918c-e134-4657-a462-9ddb810f3a1f.png)

**Comment by cabotine** [comment]
Bei Schule Delfine ist es wieder weg (nachdem ich mit der Öffentlichkeit von Studi-Sammlung gespielt habe). Wenn man "Studi Sammlung" auwählt, taucht er noch auf, was  ggf. daran liegt, dass Studi-Sammlung nicht mehr öffentlich ist, aber bei den Filtern noch gewählt werden kann.

**Comment by cabotine** [comment]
Es scheint insgesamt beim Filtern aufzutreten.

**Comment by cabotine** [comment]
Ich hab mich in Firefox abgemeldet und neu angemeldet und dann war wieder alles schön.

**Comment by phylor** [comment]
Mysteriös 🤔 Sag Bescheid wenn es wieder auftritt!
