### ISSUE TITLE
Bei den Fällen wird nur der Artikel angezeigt

### ISSUE THREAD

**Issue by wintermeyer** [wort-schule/wort.schule#298]
https://wort.schule/kind

<img width="632" alt="Bildschirm­foto 2023-03-24 um 07 23 29" src="https://user-images.githubusercontent.com/69770/227441980-e4ffbb3a-56c7-4a7c-b3cd-908b8f094a9f.png">

**Comment by phylor** [comment]
@cabotine Kann es sein, dass wenn du das Wort bearbeitest, bei den Fällen nur "Nominativ / Singular" ausgefüllt ist und der Rest leer ist?

Wenn ich alle ausgefüllt habe, werden bei mir auch alle angezeigt:

![image](https://user-images.githubusercontent.com/1394828/227557871-e32123a8-bc44-49c3-984a-ef7410908758.png)

Falls gar keine Fälle gesetzt sind, wird die ganze Box nicht angezeigt.

**Comment by cabotine** [comment]
Hah! Selber ausgetrickst, ich dachte da er Kinder findet, muss ja der Plural eingetragen sein. Der Plural ist aber in einem seperaten Feld gespeichert. Daher steht da bei Kinder tatsächlich nichts bei den anderen Formen.

**Comment by phylor** [comment]
Stimmt, Nominativ Singular und Plural speichern wir doppelt: `Noun#name`, `Noun#plural` und dann auch als `Noun#case_1_singular` und `Noun#case_1_plural`.

@wintermeyer Falls du es für wichtig erachtest, könnten wir irgendwann wohl `case_1_singular` und `case_1_plural` aus der Datenbank entfernen.

**Comment by wintermeyer** [comment]
> @wintermeyer Falls du es für wichtig erachtest, könnten wir irgendwann wohl `case_1_singular` und `case_1_plural` aus der Datenbank entfernen.

hmmm... faktisch brauchen wir für eine bessere Suche ein optimiertes Datenbankmodell. Irgendwann kommen wir nicht drum rum, aber aktuell geht es noch so. Ist Budget Problem. Ich werde das mal mit @cabotine besprechen. Wenn es so weit ist, müssen wir uns dieses Ticket noch mal vornehmen.
