### ISSUE TITLE
Stichwortsuche führt zu Fehler

### ISSUE THREAD

**Issue by cabotine** [wort-schule/wort.schule#300]
https://wort.schule/seite/search?is_filter_open=true&filterrific%5Bfilter_home%5D=&filterrific%5Bfilter_type%5D=&filterrific%5Bfilter_wordstarts%5D=&filterrific%5Bfilter_wordcontains%5D=&filterrific%5Bfilter_wordends%5D=&filterrific%5Bfilter_syllablescontains%5D=&filterrific%5Bfilter_letters%5D=&filterrific%5Bfilter_source%5D=&filterrific%5Bfilter_topic%5D=&filterrific%5Bfilter_hierarchy%5D=&filterrific%5Bfilter_consonant_vowel%5D=&filterrific%5Bfilter_phenomenons%5D%5Bconjunction%5D=and&filterrific%5Bfilter_phenomenons%5D%5Bphenomenons%5D%5B%5D=&filterrific%5Bfilter_strategies%5D%5Bconjunction%5D=and&filterrific%5Bfilter_strategies%5D%5Bstrategies%5D%5B%5D=&filterrific%5Bfilter_keywords%5D%5Bconjunction%5D=and&filterrific%5Bfilter_keywords%5D%5Bkeywords%5D%5B%5D=&filterrific%5Bfilter_keywords%5D%5Bkeywords%5D%5B%5D=1861&filterrific%5Bfilter_foreign%5D=0&filterrific%5Bfilter_prototype%5D=0&filterrific%5Bfilter_compound%5D=0&filterrific%5Bfilter_example_sentences%5D=0&filterrific%5Bfilter_singularetantum%5D=0&filterrific%5Bfilter_pluraletantum%5D=0&filterrific%5Bfilter_subjectless%5D=0&filterrific%5Bfilter_perfect_haben%5D=0&filterrific%5Bfilter_perfect_sein%5D=0&filterrific%5Bfilter_modal%5D=0&filterrific%5Bfilter_strong%5D=0&filterrific%5Bfilter_irregular_declination%5D=0&filterrific%5Bfilter_absolute%5D=0&filterrific%5Bfilter_irregular_comparison%5D=0

Wenn ich ein Stichwort eingebe danach filtere komme ich zu dieser Seite oben. 
Wenn ich dann in dem Suchfeld oben tippe, kommt eine Fehlerseite ("technischer Fehler").
Tritt auch in einem privaten Modus-Fenster auf.
Falls ich ein Video machen soll, sagt gerne Bescheid, auf dem Desktop werden sie nur schnell größer als 10 MB und können daher hier nicht eingefügt werden.

Der Cursor hüpft nach einem eingegebenen Stichwort nach oben ins Suchfeld. Man will aber tendenziell mehrere Stichwörter eingeben, daher wäre es gut, wenn er dort bei den Stichworten bleiben würde.

**Comment by wintermeyer** [comment]
![ScreenFlow](https://user-images.githubusercontent.com/69770/227712666-b1a416bc-100d-4730-a0ba-79f49e10ac28.gif)

**Comment by cabotine** [comment]
Das passiert auch bei anderen Feldern in der erweiterten Suche (z.B. KVKV-Struktur).

**Comment by cabotine** [comment]
Könntet ihr das mit als nächstes fixen? Das wäre super, weil man es dann anderen Menschen in Ruhe zeigen kann. Könnt ihr die anderen erweiterten Suchfelder auch jeweils einmal checken?
