### ISSUE TITLE
Twitter-Cards

### ISSUE THREAD

**Issue by cabotine** [wort-schule/wort.schule#301]
Nicht wichtig, nicht besonders umfangreich aber ggf. sehr hilfreich um die Seite im Twitter-Lehrerzimmer bekannt zu machen.

```
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:site" content="@wortschule">
<meta name="twitter:title" content=""das Zebra" - in Wort.Schule, dem inklusiven Wörterbuch">
<meta name="twitter:description" content="Aussprache, Schreibweise und viel mehr findest du unter Wort.Schule/">
<meta name="twitter:image" content="https://wort.Schule">

```
Das Wort und das Link zum Bild müsste ergänzt werden.

Hier kann man überprüfen, ob es eine valide Twitter-card ist.
https://cards-dev.twitter.com/validator

**Comment by xamiam** [comment]
Checked https://socialsharepreview.com/ ?

**Comment by wintermeyer** [comment]
@phylor Lass uns das die nächsten Wochen/Monate mal in einem Call besprechen.

**Comment by phylor** [comment]
Aus dem Treffen von heute: wir setzen OpenGraph Tags und testen wie es überall aussieht, d.h. auf Social Media und in Messengern

**Comment by wintermeyer** [comment]
> Aus dem Treffen von heute: wir setzen OpenGraph Tags und testen wie es überall aussieht, d.h. auf Social Media und in Messengern

**überall** ist ein Wort, das ich hier nicht benutzen würde. 😂

**Comment by xamiam** [comment]
Vielleicht reicht auch das hier:

https://socialsharepreview.com/

;)
