### ISSUE TITLE
Artikel vor Pluralform

### ISSUE THREAD

**Issue by wintermeyer** [wort-schule/wort.schule#309]
@cabotine Macht es hier mehr Sinn "Kinder" mit dem Artikel anzuzeigen?

<img width="985" alt="Bildschirm­foto 2023-04-04 um 08 39 11" src="https://user-images.githubusercontent.com/69770/229708736-8ce522bc-77b7-403a-ab7d-eda200302ddf.png">

**Comment by cabotine** [comment]
Ja gerne.
