### ISSUE TITLE
Omni Suche | Phonetische Suchresultate verwenden und an Schluss sortieren

### ISSUE THREAD

**Issue by phylor** [wort-schule/wort.schule#314]

**Comment by cabotine** [comment]
Ich muss das leider nochmal aufmachen.
Können wir bitte eine Lösung finden, dass die Nähe zum gesuchten Wort (bzw. dessen Plural) berücksichtigt?
https://www.postgresql.org/docs/current/pgtrgm.html

![grafik](https://user-images.githubusercontent.com/8180537/233841980-af4ebe22-a2f1-44d2-9ccc-1a9b7455ce0d.png)
Das erst die ganzen Wörter kommen die so weit weg vom gesuchten sind, ist problematisch.

Bei Kend (statt Kind) wird es noch offensichtlicher:
![grafik](https://user-images.githubusercontent.com/8180537/233842100-47116bbf-e5f4-4c35-ad88-b1308dd30b84.png)

**Comment by wintermeyer** [comment]
Siehe https://github.com/wort-schule/wort.schule/issues/325
`pg_trgm` schauen wir uns in einem späteren Schritt an.

@cabotine Kannst Du Dir bitte https://github.com/wort-schule/wort.schule/issues/318 anschauen?
