### ISSUE TITLE
Index page with words of same spelling

### ISSUE THREAD

**Issue by phylor** [wort-schule/wort.schule#33]
Add an index page for words with the same spelling. For example `Ticken` and `ticken`. The page should show a list of all these words and link to them.

## Todos

* [x] ~~Add index page with list of words~~ We use the search feature for that.
* [x] Add "x weitere Bedeutungen" to the detail page of a word, if there are more words with the same spelling

Follow up of #11.

**Comment by wintermeyer** [comment]
We can use the search for that? For the given example:

https://wort.schule/search?filterrific%5Bfilter_type%5D=&filterrific%5Bfilter_wordstarts%5D=Ticken&filterrific%5Bfilter_wordcontains%5D=&filterrific%5Bfilter_wordends%5D=&filterrific%5Bfilter_syllablescontains%5D=&filterrific%5Bfilter_letters%5D=&filterrific%5Bfilter_source%5D=&filterrific%5Bfilter_topic%5D=&filterrific%5Bfilter_hierarchy%5D=&filterrific%5Bfilter_consonant_vowel%5D=&filterrific%5Bfilter_phenomenons%5D%5Bconjunction%5D=and&filterrific%5Bfilter_phenomenons%5D%5Bphenomenons%5D%5B%5D=&filterrific%5Bfilter_strategies%5D%5Bconjunction%5D=and&filterrific%5Bfilter_strategies%5D%5Bstrategies%5D%5B%5D=&filterrific%5Bfilter_keywords%5D%5Bconjunction%5D=and&filterrific%5Bfilter_keywords%5D%5Bkeywords%5D%5B%5D=&filterrific%5Bfilter_foreign%5D=0&filterrific%5Bfilter_prototype%5D=0&filterrific%5Bfilter_compound%5D=0&filterrific%5Bfilter_example_sentences%5D=0&filterrific%5Bfilter_singularetantum%5D=0&filterrific%5Bfilter_pluraletantum%5D=0&filterrific%5Bfilter_subjectless%5D=0&filterrific%5Bfilter_perfect_haben%5D=0&filterrific%5Bfilter_perfect_sein%5D=0&filterrific%5Bfilter_modal%5D=0&filterrific%5Bfilter_strong%5D=0&filterrific%5Bfilter_irregular_declination%5D=0&filterrific%5Bfilter_absolute%5D=0&filterrific%5Bfilter_irregular_comparison%5D=0

**Comment by wintermeyer** [comment]
What I meant: Shouldn't we use search for that? It is a very fast implementation and the user can use the search to filter. Win-Win.

**Comment by phylor** [comment]
> What I meant: Shouldn't we use search for that? It is a very fast implementation and the user can use the search to filter. Win-Win.

Yes, that's a good idea!

We might need an "exact match" though in the search. In the `Ticken` example, we would also find `tickend` (it doesn't exist on production, but in theory we'd find it).

Does that matter?

If it does, we could add either another input field for an exact match, or we could support some very basic regex. For example `$` to specify that the word must end.

**Comment by wintermeyer** [comment]
> We might need an "exact match" though in the search. In the `Ticken` example, we would also find `tickend` (it doesn't exist on production, but in theory we'd find it).
> 
> Does that matter?

hmmm... of course it matters. But I think we can live with that because it is much faster to implement. Let's call this a feature. 😉
