### ISSUE TITLE
Cursor in der erweiterten Suche bei Stichworten

### ISSUE THREAD

**Issue by cabotine** [wort-schule/wort.schule#351]
Es ist im weiteren Sinne verwandt mit:
https://github.com/wort-schule/wort.schule/issues/339
Der Cursor verlässt das Stichwortfeld, wenn ich ein Stichwort ausgewählt habe. Ein häufiges Szenario ist jedoch, dass ich mehrere Stichworte nacheinander auswählen möchte, ohne jedes Mal wieder auf das Stichwortfeld zu klicken.

**Comment by wintermeyer** [comment]
Das Problem: Das Eingabefeld verliert den Fokus nach dem Update der Ergebnisse.

![ScreenFlow](https://github.com/wort-schule/wort.schule/assets/69770/1aa8b6d8-e9a9-49e3-8c5d-de50f28fa35a)

**Comment by cabotine** [comment]
DANKE!

**Comment by cabotine** [comment]
Ich liebe(!) die neuen Filter.
Das Problem mit dem springenden Cursor ist jedoch wieder zurück.
Das betrifft alle Felder, sobald ich einen Buchstaben eingebe, sucht er los (was toll ist) und verliert aber den Fokus.
