### ISSUE TITLE
Audiofile wird nicht automatisch bei neuem Wort generiert

### ISSUE THREAD

**Issue by cabotine** [wort-schule/wort.schule#352]
Ich habe ein neues Wort angelegt und es wird nicht veraudiosiert: https://wort.schule/leitgebend
Woran könnte das liegen?

**Comment by cabotine** [comment]
@wintermeyer kannst du hier auch noch mal gucken?

**Comment by wintermeyer** [comment]
@phylor Kannst Du mir auf die Sprünge helfen, wie das getriggert wird?

**Comment by phylor** [comment]
Das ist ein `after_save` auf `Word`:

https://github.com/wort-schule/wort.schule/blob/67beda3693e9cb29d7c600d79e255e84a5884e15/app/models/word.rb#L81

Lokal wird bei mir der Job ausgeführt, auch beim Erstellen von Wörtern. Könnte auch mit #422 zusammenhängen.

Ansonsten: läuft Good Job (`bundle exec good_job`) auf dem Server? Ist die Google API korrekt konfiguriert (credentials)?

**Comment by phylor** [comment]
@cabotine Bei neuen Wörtern wird das Audio nun generiert. Da es im Hintergrund generiert wird, musst du nach dem Speichern des Wortes die Seite nochmals neu laden, bevor das Audio angezeigt wird.

Bei Wort-Änderungen wird das Audio noch nicht aktualisiert - das lösen wir in #434.
