### ISSUE TITLE
Changing the picture does not work

### ISSUE THREAD

**Issue by cabotine** [wort-schule/wort.schule#395]
If you want to change the picture of a word, the newly uploaded picture does not replace an existing picture.
https://wort.schule/bauer

Tried it with this one:
![Bauer 4c](https://github.com/wort-schule/wort.schule/assets/8180537/12ab78d6-d9f6-45a9-990b-058fbe9c43fe)

**Comment by phylor** [comment]
@cabotine Unfortunately, I can't reproduce it locally. The image is uploaded and stored fine.

I assume you don't get any error, right? Does the upload work for words without an image? Can you replace the image of any other word?

**Comment by cabotine** [comment]
7:54 on 30th of August I have tried it again.
The upload works for a new picture for a word that has no image so far.

**Comment by cabotine** [comment]
@wintermeyer can you look into this again?

**Comment by wintermeyer** [comment]
To-Do: Cronjob überprüfen

Siehe #352 #434

**Comment by phylor** [comment]
@cabotine Replacing an image works fine for me now. Please have another look!

**Comment by cabotine** [comment]
Yes. It does! Thank you!

Am Mi., 15. Mai 2024 um 08:48 Uhr schrieb Serge Hänni <
***@***.***>:
