### ISSUE TITLE
Stichwörterfeld verliert Fokus - Cursor nach Suche zurück auf das Feld setzen

### ISSUE THREAD

**Issue by cabotine** [wort-schule/wort.schule#436]
Wenn ich ein Stichwort eingegeben habe, dann springt der Fokus aus dem Feld. Ein häufiges Szenario ist jedoch, dass man mehrere Stichwörter hintereinander eingeben will. Daher wäre es super, wenn der Fokus auf dem Feld bleiben kann.

https://github.com/wort-schule/wort.schule/assets/8180537/8c50b503-fc9b-4eca-bbb2-653b1a426490

**Comment by phylor** [comment]
@cabotine Könntest du bitte nochmals testen? Ist dies immer noch ein Problem?

Bei mir klappt's (abgesehen davon, dass es die Stichwörter umsortiert - aber der Fokus geht nicht verloren):

![screengrab-20240517-2105](https://github.com/wort-schule/wort.schule/assets/1394828/0f171f7b-d963-4ff6-86de-f6ef5e62af2e)

**Comment by frankjmueller** [comment]
Ja, jetzt funktioniert es super. Danke!
Leider verdeckt es in der mobilen Ansicht die Anzeige der Ergebnisse. ( Ich hab ein neues Issue gemacht https://github.com/wort-schule/wort.schule/issues/457)
