### ISSUE TITLE
Anpassbare Detailseite

### ISSUE THREAD

**Issue by cabotine** [wort-schule/wort.schule#440]
Die Detailseite sollte mit Liquid anpassbar sein:
https://github.com/wort-schule/wort.schule/issues/153

Dazu gehören:
Anpassbarkeit der Reihenfolge der Boxen

und dann die bereits skizzierten Aspekte:
- Silbenbögen (am besten über die Schrift)
- Farbkodierung des Geschlechts vor dem Artikel (bunte Punktgrafik)
- Symbole von Montessori (Wortarten) 
- Symbole von Fresch
- wählbare Schrift.

**Comment by wintermeyer** [comment]
@cabotine Hattest Du mir die Symbole und Farben schon geschickt?

**Comment by wintermeyer** [comment]
Mental Note: Copyright bei den Symbolen beachten.

**Comment by wintermeyer** [comment]
> wählbare Schrift

@cabotine Hast Du eine Liste von gewünschten Schriftarten die wir zur Auswahl stellen sollen?

**Comment by frankjmueller** [comment]
Ja, hatte ich. Ich such sie nochmal raus. Sie sind von Scott gezeichnet, insofern sollte es keine Copyright Probleme geben. (cc-0).
Die Schriften schicke ich auch nochmal.

**Comment by wintermeyer** [comment]
> Sollen wir uns da einmal zusammensetzen?

Einladung ist per E-Mail raus.

**Comment by phylor** [comment]
@cabotine Vielen Dank für die Hinweise! Ist soweit implementiert, mit Ausnahme der zu diskutierenden Themen: Silbenbögen und Liquid Template.

**Comment by cabotine** [comment]
Bei der Anpassbarkeit stand ja auch die Bezeichnung von den Wortarten/des Geschlechts noch aus: https://github.com/wort-schule/wort.schule/issues/111

**Comment by cabotine** [comment]
Es wäre toll, wenn ich die Einstellungen für Anzeige/Reihenfolge von Boxen und Inhalten, die Schriftart und die Bezeichnung von Wortarten/Geschlecht als Preset abspeichern könnte und dann auch per URL-Parameter übergeben werden könnte, der dann in einem Cookie gespeichert wird.
Dann könnte ich/eine Lehrkraft verschiedene Presets zur Verfügung stellen, ohne Accounts anlegen zu müssen... 
Das würde die Einsatzschwelle deutlich senken. Nur eine Idee, die mir beim Wandern kam, können wir am Mittwoch oder so nochmal besprechen.

**Comment by phylor** [comment]
@cabotine @wintermeyer Mir ist grundsätzlich aufgefallen, dass wir das Liquid Template bereits als "Wortkarten" implementiert hatten. In einer Lerngruppe kann das Wortkarten-Template gesetzt werden. Dies ersetzt dann die Detailseite eines Wortes (für alle Schüler:innen dieser Lerngruppe).

Ich denke es stellt sich dann die Frage wie wir diese Templates vereinfachen können bzw. welche Liquid Variablen dort fehlen.

> Es wäre toll, wenn ich die Einstellungen für Anzeige/Reihenfolge von Boxen und Inhalten, die Schriftart und die Bezeichnung von Wortarten/Geschlecht als Preset abspeichern könnte und dann auch per URL-Parameter übergeben werden könnte, der dann in einem Cookie gespeichert wird. Dann könnte ich/eine Lehrkraft verschiedene Presets zur Verfügung stellen, ohne Accounts anlegen zu müssen... Das würde die Einsatzschwelle deutlich senken. Nur eine Idee, die mir beim Wandern kam, können wir am Mittwoch oder so nochmal besprechen.

Momentan sind die Informationen in der Lerngruppe gespeichert und für alle Schüler:innen in dieser Lerngruppe gültig. Wir könnten dort die Presets anbieten um die einzelnen Parameter einfacher setzen zu können.

**Comment by frankjmueller** [comment]
Achso, ja das hatte ich auf dem Schirm, dass das quasi schonmal fertig war. Ich glaube es geriet dann in Vergessenheit als Max das neue Detailseitendesign entworfen hat.
Cool wäre halt, wenn man quasi ohne Registrierung draufzugreifen könnte, weil das schon eine große Hürde ist für viele.

**Comment by wintermeyer** [comment]
> Achso, ja das hatte ich auf dem Schirm, dass das quasi schonmal fertig war.

Ich hatte es bei der Kalkulation schon auf dem Schirm. ;-)

> Cool wäre halt, wenn man quasi ohne Registrierung draufzugreifen könnte, weil das schon eine große Hürde ist für viele.

Lass uns das am Mittwoch mal im Call besprechen. Mir ist gerade noch nicht klar, wie das ganz ohne Registrierung funktionieren soll.

@phylor Kannst Du in der Einladung noch auf Ja oder Nein klicken? Dann weiß ich, ob das so funktioniert. Habe Mittwoch noch Folgetermine.

**Comment by phylor** [comment]
Aus dem Treffen von heute.

- Silbenbögen und Wort-Rendering
  - [ ] Silbenbögen mit Spezialschrift rendern und CSS Implementierung entfernen
  - [ ] Falls keine Spezialschrift ausgewählt ist, Druckschrift als Fallback verwenden (falls Silbenbögen aktiviert sind)
  - [ ] Mit Ruby Schriftbreiten berechnen (ttfunk) und korrekte Länge der Silbenbögen wählen
  - [ ] Für Silbenbögen in HTML, siehe https://inklusiv.digital/bla.html
  - [ ] Linke Hälte des Hauses vor Wort anzeigen (an-/abstellbar)
  - [ ] Horizontale Linien anzeigen (an-/abstellbar)
  - [ ] Blau/rote Hervorhebung bei Silbenbögen
- Presets
  - [ ] Die jetzigen Parameter auf der Lerngruppe als `WordViewSettings` extrahieren
  - [ ] Presets können öffentlich oder privat sein. Öffentliche Presets dürfen nur Admins erstellen
  - [ ] In der Lerngruppe kann man neu ein Preset auswählen (eigene private und öffentliche)
  - [ ] Zusätzlich im Preset konfigurierbar
    - [ ] Haus ja/nein
    - [ ] Silbenbögen ja/nein
    - [ ] Blau/rote Silbenbögen ja/nein
    - [ ] Horizontale Linien ja/nein
    - [ ] Benennung Wortart
    - [ ] Benennung Geschlecht
    - [ ] Montessori Symbole ja/nein
    - [ ] Fresch Symbole ja/nein
    - [ ] Geschlechter Symbole ja/nein
  - [ ] Presets sind per URL einstellbar: https://wort.schule/seite/ansicht/2
  - [ ] Presets werden aus dem Cookie oder der Lerngruppe gewählt
  - [ ] Presets evt. auf dem User speichern und im Profil auswählbar machen?
- Liquid Template
  - [ ] Boxen als Variablen einfügen
  - [ ] Header Box als Variable einfügen
- Benennung Wortarten
  - [ ] Fixe Liste hinterlegen
  - [ ] Wortarten werden immer als Gruppe gesetzt
- Benennung Geschlechter
  - [ ] Fixe Liste hinterlegen
- Punktgrafik Geschlechter
  - [ ] Punktgrafiken hinterlegen

**Comment by phylor** [comment]
@cabotine Wenn du als Admin eingeloggt bist, kannst du dir unter folgendem Link die Silbenbögen auf einer Demoseite anschauen: https://wort.schule/seite/font

Wir zeigen dort alle Silben aus dem System. Oben kannst du die Schriften umschalten.

Wir berechnen die Textbreite und schliessen dann von dieser auf den zu verwendenden Silbenbogen. Welche Textbreiten welche Silbenbögen verwenden ist hier definiert: https://github.com/wort-schule/wort.schule/blob/82898954496a90290ee09cc58d0abb24219eef72/app/services/fonts.rb#L13

`(0..300) => "01",` bedeutet z.B., dass alle Textbreiten zwischen 0 und 300 den Silbenbogen `^01` verwenden. Die Textbreiten siehst du auf der Demoseite für jede Silbe unter "Calculated width".

Ich habe die Zuordnung versucht für die Druckschrift (DRBuch) zu machen. Dieselbe Zuordnung klappt für die meisten anderen Schriften auch - die variable Schrift braucht jedoch eine eigene Zuweisung. Dort sind die Bögen nun meist zu lang.

Könntest du bitte bei Gelegenheit über die Druckschrift schauen und mir sagen ob die Bögen so passen oder kürzer/länger sein müssen? Falls das passt würde ich die Zuweisung für die variable Schrift noch korrigieren.

**Comment by frankjmueller** [comment]
Das ist toll. Bei den längeren Bögen der Druckschrift (ab 37) gibt es manchmal noch rechts überstehende Silbenreste. Man kann es gut sehen, wenn man die Silbe markiert.
Aber im Großen und Ganzen ist es prima. Danke!
Für das Finetuning könnte ich sonst auch nochmal Anna oder Julia bitten.

**Comment by frankjmueller** [comment]
Kann es sein, dass sie Schriften auf dem Server noch fehlen?
![grafik](https://github.com/wort-schule/wort.schule/assets/163656194/6de80553-922b-4306-ba90-22bdb1f7a3a3)
![grafik](https://github.com/wort-schule/wort.schule/assets/163656194/a1bbc8c6-a574-4b9f-91d3-83ebdf01d65a)



Und es fehlen noch die Möglichkeit Boxen und Inhalte von Boxen auszublenden (z.B. Pluralwort/Singularwort usw.), oder habe ich das übersehen? Insofern kann das Issue eigentlich doch noch nicht zu sein oder?

**Comment by phylor** [comment]
> Kann es sein, dass sie Schriften auf dem Server noch fehlen?

Die Schriften werden aktuell nur bei den Silben verwendet:

<img width="636" alt="image" src="https://github.com/wort-schule/wort.schule/assets/1394828/d5413edf-f6c7-4095-b3ef-fa03ebf56e4a">

Möchtest du das Wort darüber auch in der Schrift haben?

<img width="396" alt="image" src="https://github.com/wort-schule/wort.schule/assets/1394828/10545b9d-76bc-494b-9e2b-5011c6782f3b">

> Und es fehlen noch die Möglichkeit Boxen und Inhalte von Boxen auszublenden (z.B. Pluralwort/Singularwort usw.), oder habe ich das übersehen? Insofern kann das Issue eigentlich doch noch nicht zu sein oder läuft das über die Themes der Wortarten?

Genau, ausblenden läuft über die Themes der Wortarten. Du kannst dort das Standard-Template übernehmen und dann rauslöschen was du nicht anzeigen willst.

**Comment by frankjmueller** [comment]
Hmmm.
Aber die Variante mit den Silben wird leider gar nicht angezeigt (ohne dass ich an den Themes gepfuscht habe), wie man auf dem Bild mit der Libelle sieht.

Außerdem ist mir noch was aufgefallen:
Können wir bitte auch noch eine Einstellung haben für Plural/Singular vzw. Einzahl/Mehrzahl. Es taucht oben auf und dann bei den Fällen und bei Pluralwort/Singularwort da müsste es auch Mehrzahlwort/Einzahlwort sein.

**Comment by frankjmueller** [comment]
@phylor Hast Du die Einstellung noch auf dem Schirm oder soll ich lieber ein neues Issue aufmachen?

Können wir bitte auch noch eine Einstellung haben für Plural/Singular vzw. Einzahl/Mehrzahl. Es taucht oben auf und dann bei den Fällen und bei Pluralwort/Singularwort da müsste es auch Mehrzahlwort/Einzahlwort sein.

> Hmmm. Aber die Variante mit den Silben wird leider gar nicht angezeigt (ohne dass ich an den Themes gepfuscht habe), wie man auf dem Bild mit der Libelle sieht.
> 
> Ah. Es liegt daran, dass die Libelle keine Silben hat.
> 
> Außerdem ist mir noch was aufgefallen: Können wir bitte auch noch eine Einstellung haben für Plural/Singular vzw. Einzahl/Mehrzahl. Es taucht oben auf und dann bei den Fällen und bei Pluralwort/Singularwort da müsste es auch Mehrzahlwort/Einzahlwort sein.

**Comment by phylor** [comment]
@frankjmueller Das hatte ich hier als Kommentar hinzugefügt: https://github.com/wort-schule/wort.schule/issues/111

Aber tatsächlich vergessen, danke fürs Erinnern! :slightly_smiling_face:

**Comment by frankjmueller** [comment]
@phylor Kann es sein, dass die Stichwörter eines Wortes nicht im Standardtemplate enthalten sind?
![grafik](https://github.com/wort-schule/wort.schule/assets/163656194/c4d77d34-472b-4887-ac83-9022aaac1dd5)

**Comment by frankjmueller** [comment]
Noch eine Frage:
Kann ich in den Templates ein Fallback setzen? Also z.B. wenn das Feld Sprechsilben leer ist (wie bei Libelle), dann zeige das Wort an. (Das unformatierte Wort selbst würde ich sonst nämlich aus manchen Templates rausnehmen, weil es sonst ja doppelt da steht.)

**Comment by frankjmueller** [comment]
Und: wie kann ich von außen auf ein öffentliches Setting verweisen? Geht das schon?
z.B. für 
https://wort.schule/seite/word_view_settings/1

**Comment by wintermeyer** [comment]
@frankjmueller Zusätzliche Fragen in schon geschlossenen Issues sind gefährlich. Im Sinne von: Gehen schnell verloren. 

Ich bin mir auch nicht sicher, ob Issues überhaupt ein gutes Format für diese Fragen sind. Vielleicht ist https://github.com/wort-schule/wort.schule/discussions besser geeignet. Issues sind eigentlich Arbeitsaufträge. Wenn die geschlossen sind, dann ist das Issue weg.

Bin auch unsicher, was der beste Weg ist.
