### ISSUE TITLE
Reihenfolge der Felder

### ISSUE THREAD

**Issue by frankjmueller** [wort-schule/wort.schule#457]
Das tolle neue Stichwortmenü verdeckt leider die Anzeige der Ergebnisse,
daher wäre es super, das Silbenfeld und das Stichwortmenü zu vertauschen.
![1000038734](https://github.com/wort-schule/wort.schule/assets/163656194/940b4d3d-4006-4fae-bd78-1ddd2fc23137)

**Comment by cabotine** [comment]
This is done aswell, isn't it?

**Comment by phylor** [comment]
@cabotine Yes!
