### ISSUE TITLE
Anmeldung funktioniert gerade nicht

### ISSUE THREAD

**Issue by frankjmueller** [wort-schule/wort.schule#461]
Wenn ich mich mit meinem Benutzernamen anmelden will, dann leitet er mich einfach wieder auf die Startseite um. Es gibt keine Fehlermeldung.
![grafik](https://github.com/wort-schule/wort.schule/assets/163656194/8e6fe8d2-0e3b-4563-a910-ac80098e7711)

 (Windows 11, Firefox, Chrome, jeweils die neueste Version)

**Comment by wintermeyer** [comment]
@phylor Did we have a device upgrade that maybe screwed this up?

**Comment by phylor** [comment]
There seems to be a problem with the cookies. When the login succeeds, the following is returned in the `set-cookie` header:

```
	["remember_user_token=...; path=/; expires=Sat, 08 Jun 2024 13:40:14 GMT; httponly; SameSite=Lax", "_wortschule_session=...; path=/; httponly; SameSite=Lax"]
```

This should be two cookies, but it seems both are wrapped in an array (starting with `["` and ending with `"]`) and returned as one.

Unfortunately, I can't reproduce the issue locally.

**Comment by phylor** [comment]
See https://github.com/rails/rails/issues/48195

We probably need to downgrade.

**Comment by phylor** [comment]
@wintermeyer Could we use puma in production as well? Or do you want to stick with unicorn?

**Comment by wintermeyer** [comment]
I don’t care. Puma is fine too.

**Comment by cabotine** [comment]
Thank you both, for fixing this quickly and also all the other stuff! I am really happy this is getting better and better.
