### ISSUE TITLE
Suchvorschläge werden auf dem iPad nicht angezeigt

### ISSUE THREAD

**Issue by cabotine** [wort-schule/wort.schule#476]
Moin,
ich habe mit dem iPad die Suche auf der Startseite ausprobiert und da werden leider die Suchvorschläge nicht während des Tippens angezeigt.
Sowohl mit der internen Bildschirmtastatur als auch mit der externen Tastatur.
Da das das häufigste Gerät in den Schulen ist, ist das schon schade.
iOS 14.4.1
Liebe Grüße

https://github.com/wort-schule/wort.schule/assets/8180537/b6b35c4b-6995-4696-a41a-6dfaec2491da

**Comment by phylor** [comment]
Klappt mit iOS 17, aber nicht mit 16 und darunter.

**Comment by cabotine** [comment]
Okay. Danke! Dann ist es mit einem Update behebbar. Ich versuche mal herauszubekommen, wie der Updatestand bei den 30.000 Geräten hier in der Stadt ist. Vermutlich sind sie aktueller als mein iPad-Koffer.

**Comment by cabotine** [comment]
Ich hab mein Gerät aktualisiert und jetzt geht es. Die Schulgeräte in Bremen laufen auch mit 17.x. Insofern wäre es für mich okay, es zu schließen.
