### ISSUE TITLE
Visuelle Navigation

### ISSUE THREAD

**Issue by phylor** [wort-schule/wort.schule#492]
1. Navigation über Stichworte visuell
  - [x] Seite erstellen mit Übersicht aller Stichworte mit Bild, sortiert nach Anzahl Wörtern
  - [x] Klick auf Stichwort: Anzeige verknüpfte Stichworte (haben wir das?), Anzeige aller Wörter dieses Stichworts
  - [x] Klick auf verknüpftes Stichwort schränkt Anzeige weiter ein (wie funktioniert das genau?)

2. Navigation über Kategorien visuell
  - [x] Seite erstellen mit allen Kategorien, deren Bildern und Anzahl Wörtern
  - [x] Bild zu Kategorie hinzufügen, bearbeiten, löschen
  - [x] Klick auf Kategorie zeigt Kategorie in gross und Liste aller Wörter (oder Suchseite, aber dann auch mit Kategoriename und Bild als Titel)

## Fragen

- [x] Zeigen wir auch Stichworte/Kategorien/Themen ohne Bild? -> ja

**Comment by frankjmueller** [comment]
ja, bitte auch Stichworte/Kategorien ohne Bild

**Comment by frankjmueller** [comment]
Huhu,
das funktioniert noch anders als gedacht, aber vermutlich ist es nur eine kleine Änderung:
Also:
Beim Eisbär ist ja zum Beispiel als Stichwörter das hier hinterlegt:
![grafik](https://github.com/wort-schule/wort.schule/assets/163656194/a01ff086-6515-4d0c-aa4b-9e78d5e50ae7)

In der Übersicht für Tier tauchen diese Stichwörter aber nicht als Stichwörter mit auf:
![grafik](https://github.com/wort-schule/wort.schule/assets/163656194/316b5364-5765-43c4-a9fd-cd8491abd84b)

Ziel wäre dass alle Stichwörter angezeigt werden, die gleichzeitig mit Tier an ein Wort vergeben sind.
So wie in der erweiterten Suche:
![grafik](https://github.com/wort-schule/wort.schule/assets/163656194/da981e2d-d509-451f-809e-2cb3f411ef31)

Wenn ich auf eins der verwandten Stichwörter klicke soll es zusätzlich oben aufgenommen werden.
![grafik](https://github.com/wort-schule/wort.schule/assets/163656194/d3e0d2d2-a4fb-4376-b642-347a236f4aae)

Dann sollen unter verwandten Stichwörter nur noch die angezeigt werden, die gemeinsam mit Tier und grau auftauchen.

Gut wäre es auch einen entfernen-Button bei den ausgewählten Stichwörtern zu haben (kann auch ein x sein) 
![grafik](https://github.com/wort-schule/wort.schule/assets/163656194/67d1131f-3997-415c-94cb-2c4b04e8e225)

Danke!

**Comment by wintermeyer** [comment]
@frankjmueller Bitte benutze "Reopen with comment" für so was oder erstelle ein neues Issue. Sonst versandet das. Ich reopen dieses Issue jetzt.

**Comment by frankjmueller** [comment]
Bei den Kategorien bin ich heute drüber gestolpert ob es nicht sinnvoll wäre eine Checkbox zu haben "Unterkategorien einblenden" die standardmäßig nicht aktiv ist.
So sind halt die Unterkategorien ggf. sehr dominant und ggf. verwirrend...
![grafik](https://github.com/wort-schule/wort.schule/assets/163656194/77bfe32c-49db-4709-9620-0a21a4fa09c4)
