### ISSUE TITLE
Detailseite wird nicht angezeigt

### ISSUE THREAD

**Issue by frankjmueller** [wort-schule/wort.schule#493]
Ich kann das Issue nicht wieder aufmachen
https://github.com/wort-schule/wort.schule/issues/440
Aber ich vermute, der Fehler hängt daran. (Firefox 127, Chrome Windows 11)
![grafik](https://github.com/wort-schule/wort.schule/assets/163656194/d9c321fa-aaa1-41ed-a085-dbea99438993)

**Comment by phylor** [comment]
@frankjmueller Entschuldige, funktioniert wieder!
