### ISSUE TITLE
Possibility to search across all word categories

### ISSUE THREAD

**Issue by cabotine** [wort-schule/wort.schule#5]
It would be really good to have a search form that is able to search all types of words, as students do not necessarily know the word type.

**Comment by wintermeyer** [comment]
@phylor Do you have an idea how to implement this?

**Comment by phylor** [comment]
@wintermeyer We already have a dedicated search page where one can search for a specific word type. What about including an "all" option there? See mockup below.

![image](https://user-images.githubusercontent.com/1394828/200185087-f0d9fa86-6ecd-4f2c-99c1-96ceca4f8e84.png)

The highlighted area in the mockup is for word type specific filters. We would just remove those if a search across all word types is performed. Currently they switch with JavaScript when you select a different word type.

**Comment by wintermeyer** [comment]
> What about including an "all" option there?

Yes, that is a good solution for this problem.

**Comment by cabotine** [comment]
And maybe a start page with an word-independent search? Because quite frankly a lot of language learners don't know or don't care about word types when searching for something (and they would not find pronouns and all the other stuff).

**Comment by wintermeyer** [comment]
> And maybe a start page with an word-independent search? 

That would be a new issue. => https://github.com/wort-schule/wort.schule/issues/15

**Comment by cabotine** [comment]
Does it include also the other words (like "and"/"or" and all those little function words (I don't know how the table is called)

**Comment by wintermeyer** [comment]
> Does it include also the other words (like "and"/"or" and all those little function words (I don't know how the table is called)

Have a look at https://wort.schule/search 
It is active on production.
