### ISSUE TITLE
Detailseite | Wortbeziehungen werden nicht angezeigt

### ISSUE THREAD

**Issue by phylor** [wort-schule/wort.schule#507]
Z.B. fehlen Stichwörter

**Comment by frankjmueller** [comment]
Achso, bei den Stichwörtern und anderen verwandten Wörtern, wäre es super, wenn die direkt auch verlinkt wären.

**Comment by phylor** [comment]
> Achso, bei den Stichwörtern und anderen verwandten Wörtern, wäre es super, wenn die direkt auch verlinkt wären.

Das machen wir schon so!

![screengrab-20240702-2150](https://github.com/wort-schule/wort.schule/assets/1394828/1bfb4e0e-5d6f-4340-818e-4244cd85f619)

**Comment by frankjmueller** [comment]
Toll!
