### ISSUE TITLE
Schluck auf 502 Bad Gateway Fehler 

### ISSUE THREAD

**Issue by frankjmueller** [wort-schule/wort.schule#518]
Huhu,
ich (und andere, die die Seite noch nie aufgerufen haben) bekomme immer mal einen 502 Bad Gateway Fehler auf unterschiedlichen Seiten. Es ist nicht nachvollziehbar nach warum und wann.

![grafik](https://github.com/wort-schule/wort.schule/assets/163656194/c04f5efc-d724-466f-814e-89ecfa6b6ef2)

**Comment by frankjmueller** [comment]
Manchmal lässt es sich mit neuladen beheben. Manchmal nicht.
Browser (Firefox, Chrome) ist egal.

**Comment by wintermeyer** [comment]
Ich schliesse dieses Issue mal für heute. Grund: Wir pushen gerade ständig neuen Code ins Repo. Dadurch wird immer ein automatisches Deployment ausgelöst. Dieser Fehler spricht sehr dafür, das gerade eine alte Version down ist und die neue Version noch nicht up.

Aber bitte halte mal ein Auge darauf und schreibe in ein neues Ticket die genaue URL und die genaue Uhrzeit. Dann können wir mal im Log nachschauen. Aber warte die nächsten Wochen bitte erst mal ab, bis wir alle (oder fast alle) Bugs beseitigt haben.
