### ISSUE TITLE
Doppelten Wortnamen entfernen

### ISSUE THREAD

**Issue by phylor** [wort-schule/wort.schule#521]
Ja, bitte. Und ein Fallback falls keine Silben vorhanden sind. Der Artikel kommt hinter das Häuschen, auch in der Spezialschrift.

_Originally posted by @frankjmueller in https://github.com/wort-schule/wort.schule/discussions/506#discussioncomment-9940464_

**Comment by frankjmueller** [comment]
Bei den Verben ist es noch doppelt drin:
![grafik](https://github.com/wort-schule/wort.schule/assets/163656194/e7add7b3-9b58-4a96-bfec-495796aaef63)
