### ISSUE TITLE
Grafiken beim Deployment

### ISSUE THREAD

**Issue by frankjmueller** [wort-schule/wort.schule#524]
Huhu,
kann es sein, dass beim Deployment Grafiken verlorengegangen sind? Wir hatten schonmal mehr hochgeladen.
Liebe Grüße
Frank J.

**Comment by phylor** [comment]
@frankjmueller Nicht bewusst und wir hatten diesbezüglich nichts verändert. Kannst du mir ein Wort nennen, wo dies aufgetreten ist?
