### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by frankjmueller** [wort-schule/wort.schule#544]
Moin, es kommt leider immer mal wieder ein Bad Gateway Error. (Firefox aktuelle Version unter Windows 11)
Wie kann man den ggf. loswerden?
Bei einem Browserwechsel tritt er nicht mehr auf (aber ich habe Chrome auch noch nicht hinreichend probiert um zu sehen ob er da nie auftritt).
Viele Grüße

https://github.com/user-attachments/assets/90a317d4-4ca8-466e-bdee-ad18890601be

**Comment by phylor** [comment]
Ich schaue mir das nochmals auf dem Server an.

Das Video zeigt einen Timestamp von 07.08.2024 10:56. Zu dem Zeitpunkt wurde meines Wissens nicht deployt.

**Comment by wintermeyer** [comment]
@frankjmueller Kannst Du "immer mal wieder" genauer fassen? Sprechen wir von 2-3 mal am Tag oder in der Woche? Darf natürlich überhaupt nicht vorkommen, aber mich würde interessieren, wie oft es vorkommt.

Nur damit ich es richtig verstehe: Es passiert von verschiedenen Rechnern und Browsern?

**Comment by wintermeyer** [comment]
@phylor Kannst Du im mina Deployment einen Logger einbauen/aufrufen, das in /var/log/syslog oder /var/log/messages so was wie "Successful deployment of wort.schule" reinschreibt?

**Comment by frankjmueller** [comment]
Auch jetzt, wenn ich die Seite neu lade (mit Shift gedrückt), passiert das noch.

Vermutlich 2-3 pro Woche.

Ja, Anna beobachtet das auch immer mal wieder. Ich weiß aber nicht was sie für einen Browser benutzt. Ich kann mal mehr Chrome verwenden.

**Comment by wintermeyer** [comment]
@phylor Wir haben irgendwann mal den Rails Webserver umgestellt. Ich kann mich nicht mehr genau dran erinnern warum. Ich glaube es war ein Rails Upgrade. Das Problem ist ja erst "relativ" neu. Ob es damit im Zusammenhang steht?

Und können wir auf Socket Kommunikation umstellen? Hier ist die aktuelle Nginx Konfiguration:

```
upstream wortschule {
        #server unix:/home/wortschule/app/shared/unicorn.sock fail_timeout=0;
        server localhost:3000;
}
```

**Comment by frankjmueller** [comment]
Ich hatte es auch früher schon immer mal, aber da habt ihr auch gesagt, dass es mit dem Deployment zu tun haben kann.

**Comment by wintermeyer** [comment]
> Nach dem Löschen der Cookies war der Fehler dann weg... vorher war er recht penetrant. Soll ich beim nächsten Mal versuchen die Cookies auszulesen?

Erst dachte ich mir: Warum? Aber jetzt denke ich mir: Schaden kann es nicht. Wenn es nach dem Löschen des Cookies funktioniert, dann kann es natürlich auch etwas damit zu tun haben. Unwahrscheinlich, aber es wäre dumm das nicht zu untersuchen. Vielleicht liegt es an der Größe des Cookies.

**Comment by wintermeyer** [comment]
Am 25. Mai haben wir auf einen neuen Rails Webserver umgestellt. Siehe https://github.com/wort-schule/wort.schule/pull/462

@frankjmueller Kannst Du Dich zufällig dran erinnern, ob es davor besser war?

@phylor Kann es an der folgenden Einstellung liegen? 

```ruby
max_threads_count = ENV.fetch("RAILS_MAX_THREADS", 5)
min_threads_count = ENV.fetch("RAILS_MIN_THREADS") { max_threads_count }
threads min_threads_count, max_threads_count
```

Irrer Gedanke: Kann es sein, das die Webseite immer populärer wird und deshalb mit der alten Konfiguration die Last nicht mehr handeln kann?

**Comment by frankjmueller** [comment]
Nein. Ich glaube nicht dass es vorher besser war. Es trat vorher auch schon immer mal auf. Ich schau mal ob ich es nochmal hinkriege. Und ich glaube auch nicht dass es an der Popularität liegt ;)

**Comment by frankjmueller** [comment]
Ich habe 10min Wörter aufgerufen und bearbeitet und da war es wieder... 
![grafik](https://github.com/user-attachments/assets/0b8823d1-1f72-4ac4-8ed2-04eff3d34d84)
Ich schau mal was mit dem Cookie ist.

**Comment by wintermeyer** [comment]
> Nein. Ich glaube nicht dass es vorher besser war. Es trat vorher auch schon immer mal auf.

Im Mai 2023 hatten wir das erste mal so ein Problem:
https://github.com/wort-schule/wort.schule/issues/297

>  Ich schau mal ob ich es nochmal hinkriege.

Reproduzierbarkeit wäre Gold!

**Comment by wintermeyer** [comment]
> Ich habe 10min Wörter aufgerufen und bearbeitet und da war es wieder... 

@frankjmueller Ich weiss, das es viel verlangt ist, aber kann Du mal schauen, ob Du die Reproduzierbarkeit des Problems hinbekommst? Also "immer wenn ich 2 x nach Polizei suche, dann 10 mal nach Apfelmus und dann noch das eine Wort ändere, dann kommt der 502"

**Comment by frankjmueller** [comment]
Der obere (wortschule_session) musste gelöscht werden. Dann ging es wieder. Der untere alleine hat nicht gereicht. Ich kann es später nochmal andersrum probieren... (Ist es ein Sicherheitsproblem die hier zu posten?)

_wortschule_session:Array
0:"7Rs7Wv2I4ZS7MX/68qGdkIpdjd+zJUupeFUcSh/8xYdenCreKWqhSX4diydXK5hFQmxi8QlOARPZAqNxwLgpatV+Ef7VqPdBgaTGiA7wmSPViJcv40+xR/JY3op8FEFgh9r53BqTQrrZnWM2t7utUtRYH2YQTLfnjWQPiaDLOKMkpMTieILFiVIPthrMN4MxeigpFI3i3p1Jy3MM3Z4yvX411ll8o/WPXUsuJQhJpBGgsVZ2JUV1XZWaDNDqalgoklhFRuT18QrKH+c2DaG5d8eMuReD6ljIgqI/ZYzToOqe1BwJ0t48768r7XQLvCUwwa0DhrjdYIVweFrgegw5DfHKt426xxp3afudLMoshIpGhk7HxSYkQ0I2/n+SwfYvRSnnJ3Oghqh7LwYfpfgK/ev+MeglP6DjnEixR1wb2WetHWpL0MaDE0VyBZMMc7VXV4Lpjvhhbx/eq+cWZmVqytP1b+F0CE8ep3+zRRIKiIizfYgqO+7d7zTraz8vPU94//1tEf9S1/UwBDbuxCZlBY/n0IheU2+f6hUu5twXei6f0RSf4fbm1fop4DJ7qilocw8y5W3es2iDeZzMoipB+R/lkQfCA2L3J8Kx87rmBAbsy/yyA+7sU++jxy65g6Fe7DoWlpbMHRSYq5Vc30w/kBG9NrQP9T6toL1FMNyt0pTc3EHCLAfoNrtQQeYwZy/5h81C01lUJnGNh/zlKsE1QZrajxzPqpT0a/pPBSsAeiFgG3roscaeYYXFhiZqaYELV/3sDtMowK0lQVFuoK62osl5FrYHAcFH3u4m1WPIOM2XWwt1fXAlmaOQR6E91S7IhS0CJGal6pYBHdJITVY8mWSIdWmW+/ZRX//NoquzU0RSeX8WcjMnckq1TEMMv2J/FrVz3pO8T12WKz0MuPTvlEGJ0EXRmB8PjdyffbSHYyDsHOdDdfN3nXfJ5cblXA2ctABYxiFFIDsMYdPDoo7hPle3MIz3u5yw8PdkidoICo+nP5X/QbsBPxI79EzOt8ulFKefwxrWcbXmhaA1hWrQjaM3ZuY1Bgie2CvCm58M3NCtcn4TN0Y5Qc6pevD72c2OEivYAj7P1H01egu45RPN7BOxeubxK7BOBkvPKeuZz3hRvqNxEW7cCwonpTnEi+6wL9yvvF1CCTtt0fdkRwz0IdV/15cRG5v2ZG3J8TZ8fL2wBeV5L5Ak0pELsYhNDQ8omjgJhiVfmIt9DTq33+617El+HGvYj4ZJ+R1InlAOtczkvEtQfPtoFvwsVOpQC+2zGy8Xgdav6PH8jypxcShdurMTswdIl9SQQS2behKQ2ZzyxOxtOg9nbpzQtdZnzM9NwTcn3qhJL6gos3OIOkNFT+KinzQsVgmIePJ23IAadUEnVN3yfC8rxgnu+zfHuIVRrhDkWTFnuLa3edohVMuGERhC7xpcROqk2gBlobj3njTL0t87kvZo2zi5eHd539KcA1DqUxiJPup2CW11LnB9E3H+C9AtV5Isc+woJjiANcbFdrCtCRnZJsZCuDAZtE8cLl79VrV3+uWf2LQyAbo9MiOBbK9q3ZuFcjMaac+j/09OccBJuO6aheduA5usEDC6N6HPvfrMsg0WsgC3ANTB2URKtAapMiMKtmoVFdz217nCuwIClKyPTtpyjOhfAyVg3mffMOjyXFSAZMtZZOcrrm2oRR63deKMaikzm93Xjny0OqMcj2lrBgkbJ5fwdRiS+xYPYQwtif6o7Oam/9lYsYcniBwpd3yq2QwnWoS4RhGtlnYRf7l6Dr20ZpjO8oY/Sa16kEAHRUtZNM0hmpL8IVzZW4jXE/deZXSIPB60Q4HNF9QwRhcH08WzKqD4d4jtiS7tiWkvEEBP5AsLOi6CM6o79U94I3cLswYW1sG0qu63S3XpWa4WqVPM5uvd26sN1EwIvNkqEkioy85XKckLoGxh5Vd0nauX5Ybu9SKDeCW9BcNaQXJvFsYLHx4ku5ED8GbnDdCtMBpFWnNWnyxfsl61Zk2Imq0XxTUBvXwgDLyWW6Agcs98+SNfheDYD39KWrSk10dK6Qvn4F4ti4MMZ80Owxhkqgp5itFRCQnrT/6yrzSnfXuR1BFrClcva2EhusLEEp1Xu1DevEFeB1CAHqWmSjJjN3koiV+amSVNwauvudtO+9kUQS1ZL6YbrNhtoYlT9IzP8v2O5SNXkjI/ljSop9Bz4qiOlXhfzfWfRNMORXbNuhMfigkw82tzMMlc0wb+zroxjqGIu+Vr7/aWqJiMCDXR6Ua23BtmR8tCuytGViHMcF7MwT6LoJVSS3g7biBf4k27/D0xnwpmQJzlaq1VqR0oP2gMyXpMxPZNq6DelqW0gvbDOsw4qMd3N0zC4KYq5HO4yDCecGsAOxxmv1avjp/ZaUUk3+R0K7xxl356+N3ptho8n9zaC2/tupcXXXyMmehxKk6N8jMT1IJSUkxAdmc5KaTf4hjL+YbuentY+boVNQ15PdpViGZZpsY7c/WOmv7hYedWNlzaO0Nw5i4onhHBUdgAqCM0dMwGpLMhYvatcPRZzw5/ZUALcZENBRprUW2UHMzESdjiKlfIL7YY+7ceLlVHQVymegBlXONJdKI3ZSVfme8H/9UbEkohYBz4ATj9zPG02WPLBSu1BU5Bahh5ssXG8scQ2suMt9ojnD+Q2sva/dsaUymwsfO5QXCSmx3rS0WwVtrwbZgDJcSmlcAHW/4Vq37LSCwTFEQqsL2hRvI8RnmZZS7X9vdcKUsraawxKDsjhvEULKMGTO7iaWG0dFZGP6NbVn1TaKmiNmMlkkd/wE64H7tVZt6BORt9bPqxJbHd+B9sVVQtPld4WyfYhPcp5wUf84Fgo6xAY6+Ap+KQHGuVlwlu7CL5YVfLLu2OnB9jrM4j2fBqoFzYpr583XmPXVNw8WsOc7anyl3P2u+wOf1dhBjOIURxEEJaFVcobaSpRxLn+3Q9MO5vbm9q49YqBaa2umfqNhG6ohc9uGaaj6sV1GaWPIvRfC+d6zIxMxCG4DVqbhYAa+fMCqxPFdlinAVIh9Y09pT0CaMpFbnymeK4R0OHGEnkPF4VD/UgM/mZsmMMr15pNAKrfEVPh6IGCZdkTEyYWF1qOYi7T/9hV9rhNlTT+5RBbFu37PC8eNCrS/FIYw7/hsbB/356XOb1ZbJau4NA2YTXz5WlDsHrRvE0SSv9jv15HVFY--aJdwCfJDasd0QgmS--WuEONAHv/G2ERcb+NFYc1w"

1:""
2:""
length:3
__proto__:Array

remember_user_token:"eyJfcmFpbHMiOnsibWVzc2FnZSI6Ilcxc3pYU3dpSkRKaEpERXlKSEZDTlhOSVIwRlFObUpqV0ZCU1RuQkdNVE5XU2k0aUxDSXhOekl6TURJMk56QTJMamd3TWpZNU16WWlYUT09IiwiZXhwIjoiMjAyNC0wOC0yMVQxMDozMTo0Ni44MDJaIiwicHVyIjoiY29va2llLnJlbWVtYmVyX3VzZXJfdG9rZW4ifX0%3D--d39c7300d074bf9cbfbfb674a040d3ad6717f40b"

**Comment by wintermeyer** [comment]
> (Ist es ein Sicherheitsproblem die hier zu posten?)

Nein.

**Comment by frankjmueller** [comment]
Bis zur Größe von 3493 gab es kein Problem. Ab dann begannen die Fehler und blieben dann auch konstant...
![grafik](https://github.com/user-attachments/assets/56a90327-33e9-41de-a59c-dc11ba329a27)
Passiert auch bei Chrome.
Wenn ich _wortschule_session lösche geht es auch da wieder.

**Comment by frankjmueller** [comment]
Vielleicht ist es die 4*1024 Byte Beschränkung (https://de.wikipedia.org/wiki/HTTP-Cookie)?

**Comment by phylor** [comment]
Danke euch beiden fürs Debuggen! :slightly_smiling_face: #546 verschiebt die Sessions in die Datenbank - damit sollten die Cookies kleiner werden und das Problem nicht mehr auftreten.

**Comment by frankjmueller** [comment]
Toll. Danke! Das freut mich.
