### ISSUE TITLE
jpgs filtern

### ISSUE THREAD

**Issue by frankjmueller** [wort-schule/wort.schule#545]
Die Kollegin hat aus Versehen die jpgs hochgeladen und nicht die pngs hochgeladen.
Gibt es einen Weg zu filtern wo jpgs und wo pngs hochgeladen sind? Landen die in einem Ordner? Könntet ihr uns eine Liste erstellen welche jpgs in dem Ordner sind?

**Comment by phylor** [comment]
Liste erstellt.

<details>
<summary>Technische Erstellung</summary>

```ruby
ActiveStorage::Blob.where(content_type: 'image/jpeg').joins(:attachments).where('attachments.record_type': 'Word').each { |blob| puts [bl
ob.filename,blob.created_at,blob.attachments.first.record.name,"https://wort.schule/#{blob.attachments.first.record.slug}","https://wort.schule/#{blob
.attachments.first.record.slug}/edit"].join(';') }; nil
```
</details>

**Comment by frankjmueller** [comment]
Super. Danke!
