### ISSUE TITLE
Buttons für Stichwortübersicht, Thematische Übersicht und Kategorien

### ISSUE THREAD

**Issue by frankjmueller** [wort-schule/wort.schule#547]
Bisher sind die Stichwortübersicht, Thematische Übersicht und die Kategorien ja noch verborgen.
Ich weiß das Stefan die Startseite aufgeräumt halten will.
Daher habe ich überlegt, ob es auf der Startseite einen Button Übersichten geben könnte unter dem Button Erweiterte Suche und dann auf den drei Seiten
jeweils oben Buttons zu Sortiert nach Stichwörtern, Sortiert nach Themen und Sortier nach Kategorien?
Was denkt ihr?

**Comment by wintermeyer** [comment]
Nur damit man in Zukunft den Startpunkt dieser Diskussion sehen kann:

<img width="353" alt="Bildschirmfoto 2024-08-10 um 14 27 22" src="https://github.com/user-attachments/assets/c4b74e10-4a75-43a5-b01c-3b1dfc06e587">

@phylor Kannst Du - nicht zeitkritisch - irgendwann mal Buttons oder Links zu Stichwortübersicht, Thematische Übersicht und Kategorien unter dem Button "erweiterte Suche" einbauen? Ich glaube wir müssen das einfach mal ausprobieren und schauen wie es sich anfühlt und benutzen lässt.

**Comment by phylor** [comment]
@frankjmueller @wintermeyer Wie wäre es so?

![image](https://github.com/user-attachments/assets/7ea550f7-542e-447d-9604-092c6bb50a1a)

![image](https://github.com/user-attachments/assets/986df57e-ca49-49b1-845f-8a7d1e027a54)

**Comment by frankjmueller** [comment]
Wäre für mich fein.

**Comment by wintermeyer** [comment]
Ich finde es auch gut. Dezent und trotzdem direkt da.

**Comment by frankjmueller** [comment]
Merged Du es dann? ;)

**Comment by wintermeyer** [comment]
Done. Sorry! 😉

Dauert ein paar Minuten bis es deployed ist.
