### ISSUE TITLE
https://wort.schule/tier zeigt Tierreich an

### ISSUE THREAD

**Issue by wintermeyer** [wort-schule/wort.schule#548]
Ich glaube das ist ein Fehler im Datensatz.

<img width="1297" alt="Bildschirmfoto 2024-08-10 um 22 43 06" src="https://github.com/user-attachments/assets/09b88b34-e366-4aa2-84ba-4290e1a056b6">

Wer ist für solche Bugs im Datensatz zuständig?

**Comment by frankjmueller** [comment]
Danke. Solche Sachen an Inhalt@wort.schule.
