### ISSUE TITLE
JSON Export

### ISSUE THREAD

**Issue by wintermeyer** [wort-schule/wort.schule#549]
https://wort.schule/schwan.json soll den Inhalt von https://wort.schule/schwan als JSON ausgeben.

@phylor Falls Du eine bessere Idee für die Route oder die Logik hast: Gerne. Ich halte die .json Endung für halbwegs intuitiv, aber kann auch mit einer anderen Lösung gut leben.

**Comment by phylor** [comment]
Das macht mit der Endung total Sinn!

Einen Index brauchst du nicht von allen Wörtern als JSON?

**Comment by wintermeyer** [comment]
Zu einem Index würde ich nicht nein sagen.
