### ISSUE TITLE
Always include the article for nouns

### ISSUE THREAD

**Issue by cabotine** [wort-schule/wort.schule#6]
It would be important to always include the article for nouns (also on the details page before the word)

**Comment by wintermeyer** [comment]
@phylor Please add this.

**Comment by phylor** [comment]
Could you maybe include a screenshot where the article is missing? Maybe we are not talking about the same details page. This is how it looks now:

![image](https://user-images.githubusercontent.com/1394828/200185969-db98c65e-c5b2-49b4-a8c1-357e0bee90d1.png)

Note that the article is missing if no genus is selected. In that case, we don't know which to show. Could this maybe be the issue?

**Comment by cabotine** [comment]
I mean in the upper left corner in front of the word.

**Comment by wintermeyer** [comment]
<img width="755" alt="Bildschirmfoto 2022-11-07 um 22 28 06" src="https://user-images.githubusercontent.com/69770/200419261-bb7d0e5b-eeb2-4e83-8c5b-97a8c74f71ab.png">

**Comment by phylor** [comment]
Thank you :slightly_smiling_face: :see_no_evil:
