### ISSUE TITLE
Brainstorming Google like Index Page

### ISSUE THREAD

**Issue by wintermeyer** [wort-schule/wort.schule#67]
@philipp-kempgen + @xamiam : We have talked about this in the last couple of days. This issue is primarily for us to discuss and brainstorm the GUI aspects. Once we finalised that it will become a coding assignment or I'll create a new issue for that. Of course everybody is welcome to participate in the discussion.

# The Problem

We have multiple pages which can be used to search. We have the main index page which defaults to a search for "Substantive" plus several pages to search for other Wortarten:

<img width="1206" alt="Bildschirm­foto 2022-11-23 um 08 52 08" src="https://user-images.githubusercontent.com/69770/203495781-d4b5490a-2a0c-4b12-9864-771beb12f8a5.png">

And we have the super search functionality:

<img width="1206" alt="Bildschirm­foto 2022-11-23 um 08 52 12" src="https://user-images.githubusercontent.com/69770/203495883-3daa566e-5701-4c0d-95dd-bd60e481cf5a.png">

That is too complex for many users. The GUI is not as simple and clean as possible. I am looking for a Google like index page which can be used to search for all Wortarten and which has the possibility to display the super search functionally. How? I do not know. That is the reason for this issue. I would like to ask everybody to participate with thoughts, sketches and screenshots of other pages which have solved it.

I want the new index page to get rid of the following things:

<img width="1206" alt="Bildschirm­foto 2022-11-23 um 08 52 08" src="https://user-images.githubusercontent.com/69770/203496491-d1b2227b-da7b-449e-bff5-e8caf5f44047.png">

The search result should display as it does currently. The super search functionality should become more intuitive (e.g. displaying the number of words for specific switches). It should hold the hand of the user.

**Comment by wintermeyer** [comment]
The normal user should be able to do searches as fast as possible without having to think too much. The power user should be nudged into playing with filters.

**Comment by wintermeyer** [comment]
Gmail does a fine job with the search and a filter. 

![ScreenFlow](https://user-images.githubusercontent.com/69770/203527777-f0ac4a13-2235-4f81-a0fe-ad3544816e63.gif)

The user can search over all emails and can click on the filter (right side of the text field) to have access to a filter which pulls down from the search field.

**Comment by cabotine** [comment]
I would speak to some German didactics people about this, to find out what makes sense for filters? As I can imagine it is rather annoying to change stuff later?

**Comment by wintermeyer** [comment]
About the user feedback:

> At a 1982 planning retreat, someone on the Mac team, “thought they should do some market research to see what customers wanted. 'No,' [Steve Jobs] replied, 'because customers don't know what they want until we've shown them.

Asking our users is important but we have to expect that they don't know what they want. We don't want to become the power search a "Gemischtwarenladen".

**Comment by wintermeyer** [comment]
So oder so ähnlich stelle ich mir die neue Startseite vor:

<img width="579" alt="Bildschirm­foto 2022-11-24 um 08 37 57" src="https://user-images.githubusercontent.com/69770/203721862-e4b67fb1-3502-4051-a810-1a5c39066865.png">

Wenn man auf den "Weitere Filter" Link klickt, klappt ein Tab Bar aus:

<img width="569" alt="Bildschirm­foto 2022-11-24 um 08 43 44" src="https://user-images.githubusercontent.com/69770/203722954-cdd2475f-75fb-4264-b0d6-6dc00cf3073c.png">

Alternativ kann man die Tab Bar auch direkt als Default anzeigen und sich damit aus Ausklappen sparen:

<img width="569" alt="Bildschirm­foto 2022-11-24 um 08 45 22" src="https://user-images.githubusercontent.com/69770/203723158-1eb9e8b4-c48b-4394-a0fe-6f82ea5709a1.png">

Ich bin mir nicht sicher, was da besser/übersichtlicher/sauberer ist.

Mit dem Radio-Button "unscharfe Suche" wird Kölner Phonetic ein- und ausgeschaltet. Die Zahlen hinter den Radio-Buttons der Wortarten zeigen direkt die möglichen Treffer an. Wenn man oben im Suchfeld Buchstaben eingibt, müssen sich diese Zahlen direkt mit ändern. Das gleiche gilt für andere Filter.

Unter dem Formular werden dann wie jetzt schon die Treffer als Kacheln angezeigt.

Meinungen?

**Comment by wintermeyer** [comment]
Jetzt habe ich tatsächlich auf Deutsch geschrieben. 🤦‍♂️ Ist aber vielleicht gar nicht so schlecht.

**Comment by wintermeyer** [comment]
Die neue Startseite würden damit ungefähr so aussehen:

<img width="1206" alt="Bildschirm­foto 2022-11-24 um 08 59 35" src="https://user-images.githubusercontent.com/69770/203726295-8d8b25ff-4fb5-4bc3-b4e9-1d4f37ed05fc.png">

Damit wird die Top Navigation Bar viel aufgeräumter. Ursprünglich wollte ich die Seite so minimal wie möglich halten. Aber vielleicht ist der Ansatz mit dem direkt angezeigten Tab Bar gar nicht so schlecht. Ein Nudge für den User auch mal mehr auszuprobieren ohne ihn direkt zu erschlagen.

**Comment by cabotine** [comment]
Looks good to me!

Show only words with images as a switch like "unscharfe Suche" would be nice.

"Unscharfe Suche" is not clear to Kids. We may think about another title ("Genaue Suche")

**Comment by cabotine** [comment]
Maybe "andere/weitere Wortarten" also as a radio Button?

**Comment by wintermeyer** [comment]
Hier noch ein Negativbeispiel. Das gleiche grundlegende Problem und eine Lösung die wenig intuitiv ist:

https://www.schulentwicklung.nrw.de/cms/grundwortschatz-nrw/grundwortschatz/wortfilter/index.html

**Comment by wintermeyer** [comment]
> Looks good to me!
> 
> Show only words with images as a switch like "unscharfe Suche" would be nice.
> 
> "Unscharfe Suche" is not clear to Kids. We may think about another title ("Genaue Suche")

I am not too happy with "unscharfe Suche" either. While thinking about it ... "Genaue Suche" has one additional advantage: We can add the number of possible matches behind the word. Like with "Substantive". By that a user gets direct feedback that this would narrow down the results.

**Comment by wintermeyer** [comment]
> Maybe "andere/weitere Wortarten" also as a radio Button?

Yes!

**Comment by philipp-kempgen** [comment]
Even though I seem to be late to the party, here's another idea.
People are trained to use Google search.
So do it like Google search.

Make the initial search page have basically nothing but a text box.

(Note: The initial search page may or may not be the same as the index page. You may want to display stuff like "word of the day", ... on the index page as side notes.)

When the user submits the form, redirect to the second search page.
The URL could be "https://wort.schule/suche?q=test" or even just "https://wort.schule/?q=test".
Make that look like Google's second search page, i.e. search bar on top, then optional filters (just the most common ones), then the results.
The results should be vertically one below the other instead of all over the page (harder to read).
Optionally display interesting stuff as side notes on the right, such as words/articles/lessons related to the first result or "did you know" random facts.

See crude mockup at
http://www.kempgen.net/tmp/wortschule/suche2.html
(demo / wort.schule.demo)

Display the number of results to expect for filters next to the respective entries in the select boxes unless the filter query is too expensive just for that number.

Limit the available filters.
Start by removing those that need expensive queries ("letters used"?).
If you want to keep the current expert search page for power users you can do that. Google does that as well. Hide it with a small button that hardly anyone except for power users will ever click.

Maybe explain in a help section how teachers can send URLs with pre-applied filters to their students, to pre-select provenience = "Bremer Rechtschreibschatz" for example (https://wort.schule/?provenience=de-hb-rss2015).

Take a look at Google image search as well.
On desktop browsers with the required JavaScript capabilities, the select boxes for the filters can be rendered as custom inputs.

**Comment by philipp-kempgen** [comment]
I like Stefans wireframe of a start page!
Not sure about how the search box isn't part of the rolodex cards though.

**Comment by wintermeyer** [comment]
> Not sure about how the search box isn't part of the rolodex cards though.

The idea is that the user can change the search query after or parallel to change the other filters.

**Comment by wintermeyer** [comment]
> Even though I seem to be late to the party, here's another idea. People are trained to use Google search. So do it like Google search.

I like the idea. But I think or hope that the current idea helps students while typing. They have a better chance of guessing how a word has to be written.

I really like your idea about displaying the results:

<img width="873" alt="Bildschirm­foto 2022-11-25 um 13 01 57" src="https://user-images.githubusercontent.com/69770/203981892-b65a66d9-1a42-4ad8-99f7-26b7800b7ca3.png">

Using a Google like schema would give us more possibilities to display information. It would solve the whole picture or no picture problem too. And it would be easier to become barrierefrei.

> Display the number of results to expect for filters next to the respective entries in the select boxes unless the filter query is too expensive just for that number.

👍

> Limit the available filters. Start by removing those that need expensive queries ("letters used"?). If you want to keep the current expert search page for power users you can do that. Google does that as well. Hide it with a small button that hardly anyone except for power users will ever click.

How does Google do that? I have never seen a power user search page.

> Maybe explain in a help section how teachers can send URLs with pre-applied filters to their students, to pre-select provenience = "Bremer Rechtschreibschatz" for example (https://wort.schule/?provenience=de-hb-rss2015).

Very good idea! => https://github.com/wort-schule/wort.schule/issues/72

> Take a look at Google image search as well. On desktop browsers with the required JavaScript capabilities, the select boxes for the filters can be rendered as custom inputs.

??? You lost me. Please share a screencast or a screenshot. Here's my Google Image Search screen:

<img width="1206" alt="Bildschirm­foto 2022-11-25 um 13 07 30" src="https://user-images.githubusercontent.com/69770/203983314-3d406d78-671f-4b48-b3e6-31fefa55c4fd.png">

**Comment by wintermeyer** [comment]
> Even though I seem to be late to the party, here's another idea. People are trained to use Google search. So do it like Google search.

OK. @philipp-kempgen is on the right track here. It took me a moment to grasp the idea/concept.

Example:

![schwan](https://user-images.githubusercontent.com/69770/203984795-5e21c5c0-ad90-4e6a-ad49-b28725f61851.gif)

This gives us the possibility to give feedback right away through the pull down menu **and** to offer a filter mechanism on the result page. 

Works for mobile views too:

![schwan-mobile](https://user-images.githubusercontent.com/69770/203985870-abff045f-7d02-46c4-82e6-ddb8daaf9885.gif)

**Comment by philipp-kempgen** [comment]
> How does Google do that? I have never seen a power user search page.

Search preferences (click the wheel icon on the results page):
https://www.google.com/preferences

Advanced search:
https://www.google.com/advanced_search

And then there's even more search options that don't have a GUI:
https://support.google.com/websearch/answer/2466433

> Here's my Google Image Search screen

Now click "Suchfilter" and you'll get a couple of filters: size (Größe), color (Farbe), type (Typ) etc. (somewhat different on mobile devices).
Those work similar to SELECT boxes in HTML, but they are implemented with JavaScript. They can thus save some space, even if the options they contain would otherwise make the whole SELECT box wider.

> and to offer a filter mechanism on the result page.

Yes!

**Comment by philipp-kempgen** [comment]
Either way: I like that sketchy wireframe look that you created. Looks playful.
You could potentially even use that look for the final HTML page.

Make it look like a chalkboard perhaps.
Just playing around:
http://www.kempgen.net/tmp/wortschule/suche2b.html
That's probably a bit over the top though and might get tiring.

**Comment by cabotine** [comment]
It would be important to include images in the search results.

**Comment by wintermeyer** [comment]
> It would be important to include images in the search results.

The Google approach makes this easier.

**Comment by wintermeyer** [comment]
Status update: I am waiting for feedback from @xamiam. With a bit of luck he will add a scribble in this issue today. Either way I'll create a new issue with the results on this discussion and a work assignment in the next couple of days.

**Comment by xamiam** [comment]
Happy Dec. 1st!

![wort schule_v1_start](https://user-images.githubusercontent.com/309421/204931330-e46d6cea-d99b-4444-b877-1082675f228f.png)

Just the look'n feel for now. Pretty similar to Google, tbh. Search results coming asap.

**Comment by wintermeyer** [comment]
I like @xamiam idea. But let's go full trottle here and add the images of the words when ever possible too:

<img width="651" alt="Bildschirm­foto 2022-12-01 um 07 05 41" src="https://user-images.githubusercontent.com/69770/204978327-d732d4b2-53d6-4bcc-bb7f-459bd093cb5a.png">

**Comment by xamiam** [comment]
![grafik](https://user-images.githubusercontent.com/309421/205024542-ef530e06-26e4-44c9-906c-bc669ea395e3.png)

Like so?

**Comment by wintermeyer** [comment]
> Like so?

@xamiam Would you mind to use real images from https://wort.schule to visualise it a bit more realistically? Thanks!

**Comment by wintermeyer** [comment]
> > Like so?
> 
> @xamiam Would you mind to use real images from https://wort.schule to visualise it a bit more realistically? Thanks!

The images don't have to match to the words. I just want to see how a image with a transparent background looks and how we display words with no image.

**Comment by xamiam** [comment]
![grafik](https://user-images.githubusercontent.com/309421/205041337-22f8defc-5025-4931-9957-b840f7487b37.png)

?

**Comment by cabotine** [comment]
I really like this approach.

**Comment by xamiam** [comment]
![wort schule_v2](https://user-images.githubusercontent.com/309421/205383306-ce1157fc-72e5-4369-a9f1-196792fb2e8c.png)

**Comment by xamiam** [comment]
![wort schule_v2-01](https://user-images.githubusercontent.com/309421/205395583-117031b0-58c7-42c8-ad4d-baea9a02624c.png)
![wort schule_v2-02](https://user-images.githubusercontent.com/309421/205395587-71adb36d-4740-4a0e-bb9c-132baa0801ee.png)
![wort schule_v2-03](https://user-images.githubusercontent.com/309421/205395588-10b5af61-bd8f-406f-a847-b9b185db9a19.png)
![wort schule_v2-04](https://user-images.githubusercontent.com/309421/205395591-41453a81-1976-4110-82e9-2efbab67abb1.png)

**Comment by wintermeyer** [comment]
@xamiam Great work. As discussed by phone: There are a couple of potential mobile first issues here.

BTW: "Über das Projekt" and "Wie funktioniert's" can move/be deleted from the top navigation bar. Let's save that real estate on mobile devises and keep everything uncluttered.

# Thoughts

We have two screens which work hand in hand. There is this one (screen #1):

<img width="417" alt="Bildschirm­foto 2022-12-03 um 10 11 21" src="https://user-images.githubusercontent.com/69770/205433454-b9fdac77-49a9-4ac8-89cb-5bda978ed31e.png">

and the result page (screen #2):

<img width="799" alt="Bildschirm­foto 2022-12-03 um 10 11 52" src="https://user-images.githubusercontent.com/69770/205433476-da7ed811-449a-4a75-b2e7-61acc557a15a.png">

We have some overlapping here. I propose to merge both. Display screen #1 initially and skip to #2 right after a user enters the first letter. We delete the logo and move the search bar a bit north. Display the results as in screen #2 shown. Maybe add a bit of animation for this. Or not (no need to make this too playful).

By that we have the clean initial screen which transform to a full search tool automatically. Without having the user to click the search button or to press the Enter key.

**Comment by xamiam** [comment]
![wort schule_v2_detailsuche](https://user-images.githubusercontent.com/309421/205458082-3cdd9583-faf4-4b55-a179-4536603b2724.png)

here's a draft for the detailed search on desktop. the mobile view could be stacked: 1. full text search, 2. detailed filters, 3. results

**Comment by wintermeyer** [comment]
@xamiam Nice!

- Please show us how that mobile view would look like. I have a hard time to imagine it.
- I'd like to present numbers where possible. e.g. Beispielsatz (1.242). So that I user gets a feeling what difference a specific filter would make for his/her search.
- I am not sure about the wording here. I am leaning to "Filter" more than to "Suche". But that is an easy fix to do later if needed.

**Comment by xamiam** [comment]
![desktop start](https://user-images.githubusercontent.com/309421/205975946-ac9e5863-06d0-47bf-aefd-6a0f1c5420de.png)
![desktop start autocomplete](https://user-images.githubusercontent.com/309421/205975941-af534b3e-6066-4473-bdbe-7e3cd5fc9a16.png)
![desktop results](https://user-images.githubusercontent.com/309421/205975940-f03b6553-2d92-4b40-85c6-6a6a10dfc3ec.png)
![desktop results filter](https://user-images.githubusercontent.com/309421/205975931-132d932b-ae47-428c-b487-363aaf0d4f0e.png)
![mobile results](https://user-images.githubusercontent.com/309421/205975949-e6e92522-e174-4300-a476-ebec4b49bd6d.png)
![mobile results filter](https://user-images.githubusercontent.com/309421/205975947-ccc588ca-ca09-4628-bf58-d03ef00a563e.png)

**Comment by cabotine** [comment]
Cool. Is it possible to have a three-way state checkbox (not selected, yes, no). That way people could select words without example sentences to add example sentences. Or I could deselect "Fremdwörter".

**Comment by wintermeyer** [comment]
> HTML input elements can be "indeterminate", and so checkboxes can indeed appear to be tri-state.

Let's keep the GUI clear and simple. There must not be any guess working on the user's side. A checkbox is a boolean. True or false. Anything else is either a radio button or a pull down menu.

**Comment by cabotine** [comment]
Okay. The main reason I was asking is: Teachers might want to exclude "Fremdwörter" from the results as those do not follow the rules of German phonetics. Can we have another solution?

**Comment by cabotine** [comment]
I can also be helpful ;) (not only create new problems)
Yesterday I spoke to an expert about the filter issue.

We figured out which are the filters useful for students:
Wortanfang, Wortende
Wort enthält (egal wo)
Silben
Kategorie (Hierarchien sichtbar machen)
Thema
Stichwörter
Wortart

Advanced filters (neccessary for teachers), those can be hidden and pop up if you click on "mehr Filter anzeigen"
Konsonante-Vokale-Folge
Verwendete Buchstaben (muss nur Wörter anzeigen die mit den Buchstaben bildbar sind)
Rechtschreibphänomene
Strategien
Quelle (sichtbar/unsichtbar)
Modellwort
Fremdwort (preferably is a Fremdwort or please no Fremdwort)
Zusammensetzung (preferably is a Zusammensetzung or please no Zusammensetzung )
Beispielsatz (preferably has an example sentence or has no example sentence)
Singular/Pluralwörter
Zahl der Silben
Reimwörter suchen (has Reimwörter)

Wortartspezifisch:
Substantive
Geschlecht
Adjektive
Absolutes Adjektiv
Unregelmäßige Komparation
Unregelmäßige Deklination
Verben
Subjektloses Verb
Starkes Verb
Perfektbildung über "haben"
Perfektbildung über "sein"

**Comment by cabotine** [comment]
Sure!
Our idea was to collapse the teachers/adult search filters in the filter pane (and only to show them if you click on "mehr Filter anzeigen").

**Comment by wintermeyer** [comment]
@xamiam Sorry that I haven't been thinking about this before. We have a problem with the pictures:

<img width="699" alt="Bildschirm­foto 2022-12-08 um 09 23 11" src="https://user-images.githubusercontent.com/69770/206395968-5bf7656c-1f00-4c7f-bac7-4c843dbd5fe7.png">

Let's face it: Most of the words don't have an image. We waste a lot of real estate. We should find a way to render the words in the result list differently. The default should be "no image". If there is an image we can display it. My idea would be to move the image from the left side to the down right corner.

**Comment by cabotine** [comment]
We also can leave out the syllables (spoke about that yesterday with my colleague). That would make stuff clearer as well.

**Comment by cabotine** [comment]
More important would be the short meaning (instead of syllables) Like Bauer (Schach), Bauer (Landwirt), Bauer (Vogelkäfig)

**Comment by wintermeyer** [comment]
See #170 and #171.
