### ISSUE TITLE
Names for nouns, verbs, adjectives should be customizable on a classroom level

### ISSUE THREAD

**Issue by cabotine** [wort-schule/wort.schule#69]
I am deeply sorry for this issue, but some teachers use "Substantiv" some "Nomen" some use something else like "Wie-Wörter" for adjectives. So it would be great if that can be decided by the teacher on the classroom level.

**Comment by wintermeyer** [comment]
That is a tricky problem so solve. 😱

@cabotine Please provide a matrix of all the possible variants in this issue.

**Comment by cabotine** [comment]
Sure. It is:
Nomen or Substantive or Namenwörter
Verben or Tunwörter
Adjektive or Wie-Wörter or Eigenschaftswörter

**Comment by wintermeyer** [comment]
Maybe it would be a good idea to use [Rails I18n](https://guides.rubyonrails.org/i18n.html) features for this. We could create sub languages for each flavour. Would keep the door open for other variants and we wouldn't have to reinvent the wheel.

**Comment by wintermeyer** [comment]
Closed by https://github.com/wort-schule/wort.schule/issues/111
