### ISSUE TITLE
Help Section for Teachers

### ISSUE THREAD

**Issue by wintermeyer** [wort-schule/wort.schule#72]
From #67 

> Maybe explain in a help section how teachers can send URLs with pre-applied filters to their students, to pre-select provenience = "Bremer Rechtschreibschatz" for example (https://wort.schule/?provenience=de-hb-rss2015).

**Comment by wintermeyer** [comment]
> If you can add the page (maybe invisible first), I can add content there.

Let's start with a Wiki page at https://github.com/wort-schule/wort.schule/wiki
Once we see how much information is in and how it is structured we can decide if we leave it in the Wiki (which would not be a bad idea) or put it into the application.

**Comment by cabotine** [comment]
Sure. How can I edit the wiki page? The link takes me back to the project start page.

**Comment by wintermeyer** [comment]
> Sure. How can I edit the wiki page? The link takes me back to the project start page.

Please try again. I created a main page. Maybe that was the missing piece. If not we have to do a screen sharing session.

**Comment by wintermeyer** [comment]
@cabotine Do you see these buttons when you visit https://github.com/wort-schule/wort.schule/wiki ? 

<img width="1185" alt="Bildschirm­foto 2022-11-27 um 16 39 41" src="https://user-images.githubusercontent.com/69770/204143944-6ccd5d2a-a292-4db4-94b1-d56e08989feb.png">

**Comment by cabotine** [comment]
Now I can see a wiki-page, but I don't have editing rights apparently.

**Comment by wintermeyer** [comment]
> Now I can see a wiki-page, but I don't have editing rights apparently.

Please try again.

**Comment by cabotine** [comment]
Now it works.

**Comment by wintermeyer** [comment]
I close this issue because of a) the Wiki is set up and b) https://github.com/wort-schule/wort.schule/issues/143
