### ISSUE TITLE
Wortlisten: The nouns should also include the "articles".

### ISSUE THREAD

**Issue by wintermeyer** [wort-schule/wort.schule#76]
I love the Wortlisten-feature. Just in the overview the nouns should also include the "articles".

![grafik](https://user-images.githubusercontent.com/8180537/204145372-36d60df2-e017-4125-b99d-ddfd834450a5.png)

_Originally posted by @cabotine in https://github.com/wort-schule/wort.schule/issues/16#issuecomment-1328279217_

**Comment by phylor** [comment]
@wintermeyer @cabotine I assume we also want to have articles in the Wörterklinik, right?

![image](https://user-images.githubusercontent.com/1394828/204148427-bf045a1f-1228-492a-ad59-29a41c85b1ab.png)

**Comment by wintermeyer** [comment]
> @wintermeyer @cabotine I assume we also want to have articles in the Wörterklinik, right?

@phylor Yes!

BTW: https://github.com/wort-schule/wort.schule/issues/76

**Comment by cabotine** [comment]
Yes, wherever we encounter a noun ;)
