### ISSUE TITLE
Automatically include the word in a content error email

### ISSUE THREAD

**Issue by cabotine** [wort-schule/wort.schule#8]
If a user clicks on report a content error, it would be nice if the word from the active page would be included in the email header automatically.

**Comment by wintermeyer** [comment]
By content error the link `[Inhaltlichen Fehler melden](mailto:inhalt@wort.schule?subject=Fehler)` is meant.

See: https://kulturbanause.de/blog/e-mail-links-mailto-mit-betreff-kopie-cc-blindkopie-bcc-und-nachrichteninhalt/
