### ISSUE TITLE
Add a hit_counter to the word model

### ISSUE THREAD

**Issue by wintermeyer** [wort-schule/wort.schule#91]
Add a `hit_counter` integer attribute to the Word model. Increase the value every time a user visits the #show page of the word. By that we should be able to bubble up the best search results in the future.

# Potential Crawler Problem

We do have the problem of search engines which would trigger the counter without being a human. To minimise that we could check for the used browser and not count the search engines we have in a black list. For those we don't have in the black list: So be it. Since each search engine will crawl to all pages the `hit_counter` will still be usable for our needs. We can fine tune this in the future (e.g. just count registered users but let's discuss that in the future).

**Comment by cabotine** [comment]
It would be great to have a statistics page as well, as we can check if certain popular words have no images or if words with images are used more often.

**Comment by wintermeyer** [comment]
> It would be great to have a statistics page as well, as we can check if certain popular words have no images or if words with images are used more often.

=> https://github.com/wort-schule/wort.schule/issues/93

**Comment by phylor** [comment]
@wintermeyer Do we track something within the session of the visitors? That is, if I visit a word and then hit refresh 10 times (or I go back and forth), we count every hit? Or do we count it only once and store it in the session for x minutes?

**Comment by wintermeyer** [comment]
> @wintermeyer Do we track something within the session of the visitors? That is, if I visit a word and then hit refresh 10 times (or I go back and forth), we count every hit? Or do we count it only once and store it in the session for x minutes?

Very good question! hmmm... let's store it in the session for the rest of the day. But no need to become religious about the exact timing. What ever is technically easy to implement. But along the idea of having one hit per day per user.

**Comment by wintermeyer** [comment]
@phylor Second thought: Maybe we can solve this easier with a validation in the model.

**Comment by phylor** [comment]
> @phylor Second thought: Maybe we can solve this easier with a validation in the model.

Please explain, I can't quite follow. We don't have access to the session in the model, right? How would we know within the validation that a different user visited the word?

**Comment by wintermeyer** [comment]
Sorry, for not explaining it better! Initially I thought about adding a `hit_counter` attribute to the `Word` model. For that we couldn't add a validation which would help here. But we could add a new model `Hit` with the attributes `user_id`, `word_id` and `date` (date wouldn't strictly being necessary). For that model we can create a validation that one user can only add one entry per day. But that would make it impossible for anonymous users to participate in the counter. 

....hmmmm...

Bad idea. Let's stick with your session idea and a simple `hit_counter` attribute.
