### ISSUE TITLE
Add logos from sponsors of the project

### ISSUE THREAD

**Issue by cabotine** [wort-schule/wort.schule#92]
Aktion Mensch, Sophie Scholl Schulen, Uni Bremen sponsor this project. Please add the following logos to the footer 
https://www.uni-giessen.de/ueber-uns/veranstaltungen/sonstige/AM_Foerderungs_Logo_RGB.png/image
https://www.sophie-scholl-schulen.de/fileadmin/resources/gfx/logos/sophieSchollSchulen.png 
https://www.uni-bremen.de/typo3conf/ext/package/Resources/Public/Images/logo_ub_2021.png
and link to 
www.aktion-mensch.de
www.sophie-scholl-schulen.de
https://www.uni-bremen.de/fb12/arbeitsbereiche/abteilung-c-inklusive-paedagogik/inklusive-paedagogik-geistige-entwicklung-und-lernen

and exchange the copyright symbol with a cc-0-Logo.
https://www.researchgate.net/profile/Donat-Agosti/publication/51971424/figure/fig2/AS:203212943564807@1425461149299/Logo-of-the-CC-Zero-or-CC0-Public-Domain-Dedication-License-No-Rights-Reserved-CC.png

**Comment by phylor** [comment]
@cabotine The first logo from uni-giessen.de doesn't load for me, it only shows `<plone.namedfile.file.NamedBlobImage object at 0x7f853ca2cc80 oid 0x520a60 in <Connection at 7f858c0d1cc0>>`

You could also paste the logo into the comments box here, and it will upload it directly into the issue.

**Comment by wintermeyer** [comment]
> @cabotine The first logo from uni-giessen.de doesn't load for me

https://www.uni-giessen.de/de/ueber-uns/veranstaltungen/sonstige/AM_Foerderungs_Logo_RGB.png

![](https://www.uni-giessen.de/de/ueber-uns/veranstaltungen/sonstige/AM_Foerderungs_Logo_RGB.png)
